// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cordicSin_fix.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cordicSin_fix::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cordicSin_fix::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state1 = "1";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state2 = "10";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state3 = "100";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state4 = "1000";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state5 = "10000";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state6 = "100000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_1 = "1";
const sc_lv<32> cordicSin_fix::ap_const_lv32_2 = "10";
const sc_lv<32> cordicSin_fix::ap_const_lv32_3 = "11";
const sc_lv<32> cordicSin_fix::ap_const_lv32_4 = "100";
const sc_lv<1> cordicSin_fix::ap_const_lv1_0 = "0";
const sc_lv<32> cordicSin_fix::ap_const_lv32_5 = "101";
const sc_lv<8> cordicSin_fix::ap_const_lv8_0 = "00000000";
const sc_lv<8> cordicSin_fix::ap_const_lv8_4D = "1001101";
const sc_lv<4> cordicSin_fix::ap_const_lv4_0 = "0000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_3F = "111111";
const sc_lv<32> cordicSin_fix::ap_const_lv32_34 = "110100";
const sc_lv<32> cordicSin_fix::ap_const_lv32_3E = "111110";
const sc_lv<1> cordicSin_fix::ap_const_lv1_1 = "1";
const sc_lv<54> cordicSin_fix::ap_const_lv54_0 = "000000000000000000000000000000000000000000000000000000";
const sc_lv<63> cordicSin_fix::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> cordicSin_fix::ap_const_lv12_433 = "10000110011";
const sc_lv<32> cordicSin_fix::ap_const_lv32_B = "1011";
const sc_lv<9> cordicSin_fix::ap_const_lv9_0 = "000000000";
const sc_lv<12> cordicSin_fix::ap_const_lv12_FF9 = "111111111001";
const sc_lv<12> cordicSin_fix::ap_const_lv12_7 = "111";
const sc_lv<12> cordicSin_fix::ap_const_lv12_36 = "110110";
const sc_lv<32> cordicSin_fix::ap_const_lv32_1F = "11111";
const sc_lv<8> cordicSin_fix::ap_const_lv8_FF = "11111111";
const sc_lv<4> cordicSin_fix::ap_const_lv4_A = "1010";
const sc_lv<4> cordicSin_fix::ap_const_lv4_1 = "1";
const sc_lv<8> cordicSin_fix::ap_const_lv8_80 = "10000000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_7 = "111";
const sc_lv<3> cordicSin_fix::ap_const_lv3_0 = "000";
const sc_lv<7> cordicSin_fix::ap_const_lv7_0 = "0000000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_E = "1110";
const bool cordicSin_fix::ap_const_boolean_1 = true;

cordicSin_fix::cordicSin_fix(sc_module_name name) : sc_module(name), mVcdFile(0) {
    arctan_V232_U = new cordicCos_fix_arckbM("arctan_V232_U");
    arctan_V232_U->clk(ap_clk);
    arctan_V232_U->reset(ap_rst);
    arctan_V232_U->address0(arctan_V232_address0);
    arctan_V232_U->ce0(arctan_V232_ce0);
    arctan_V232_U->q0(arctan_V232_q0);
    top_level2_fpext_lbW_U63 = new top_level2_fpext_lbW<1,2,32,64>("top_level2_fpext_lbW_U63");
    top_level2_fpext_lbW_U63->clk(ap_clk);
    top_level2_fpext_lbW_U63->reset(ap_rst);
    top_level2_fpext_lbW_U63->din0(x);
    top_level2_fpext_lbW_U63->ce(ap_var_for_const0);
    top_level2_fpext_lbW_U63->dout(grp_fu_144_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_F2_fu_214_p2);
    sensitive << ( zext_ln461_fu_174_p1 );

    SC_METHOD(thread_add_ln581_fu_236_p2);
    sensitive << ( F2_fu_214_p2 );

    SC_METHOD(thread_add_ln703_fu_538_p2);
    sensitive << ( p_Val2_75_reg_123 );
    sensitive << ( zext_ln703_fu_477_p1 );

    SC_METHOD(thread_and_ln581_fu_322_p2);
    sensitive << ( icmp_ln581_reg_637 );
    sensitive << ( xor_ln582_fu_316_p2 );

    SC_METHOD(thread_and_ln582_fu_307_p2);
    sensitive << ( icmp_ln582_reg_650 );
    sensitive << ( xor_ln571_fu_302_p2 );

    SC_METHOD(thread_and_ln585_7_fu_339_p2);
    sensitive << ( and_ln581_fu_322_p2 );
    sensitive << ( xor_ln585_fu_333_p2 );

    SC_METHOD(thread_and_ln585_fu_327_p2);
    sensitive << ( and_ln581_fu_322_p2 );
    sensitive << ( icmp_ln585_fu_279_p2 );

    SC_METHOD(thread_and_ln603_fu_356_p2);
    sensitive << ( icmp_ln603_fu_284_p2 );
    sensitive << ( xor_ln581_fu_350_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln99_fu_438_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln99_fu_438_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln99_fu_438_p2 );
    sensitive << ( z_i_old_V_reg_99 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_arctan_V232_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln100_fu_450_p1 );

    SC_METHOD(thread_arctan_V232_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ashr_ln586_fu_293_p2);
    sensitive << ( man_V_12_reg_626 );
    sensitive << ( zext_ln586_fu_289_p1 );

    SC_METHOD(thread_bitcast_ln696_fu_390_p1);
    sensitive << ( x );

    SC_METHOD(thread_exp_tmp_V_fu_164_p4);
    sensitive << ( ireg_V_fu_148_p1 );

    SC_METHOD(thread_icmp_ln571_fu_208_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( trunc_ln556_fu_152_p1 );

    SC_METHOD(thread_icmp_ln581_fu_230_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_54_fu_220_p4 );

    SC_METHOD(thread_icmp_ln582_fu_256_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( F2_fu_214_p2 );

    SC_METHOD(thread_icmp_ln585_fu_279_p2);
    sensitive << ( sh_amt_reg_643 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln603_fu_284_p2);
    sensitive << ( tmp_55_reg_662 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln99_fu_438_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ush_reg_133 );

    SC_METHOD(thread_ireg_V_fu_148_p1);
    sensitive << ( grp_fu_144_p1 );

    SC_METHOD(thread_lhs_V_4_fu_518_p3);
    sensitive << ( z_i_old_V_reg_99 );

    SC_METHOD(thread_lhs_V_fu_494_p3);
    sensitive << ( z_r_old_V_reg_111 );

    SC_METHOD(thread_man_V_11_fu_194_p2);
    sensitive << ( p_Result_84_fu_190_p1 );

    SC_METHOD(thread_man_V_12_fu_200_p3);
    sensitive << ( p_Result_84_fu_190_p1 );
    sensitive << ( p_Result_s_fu_156_p3 );
    sensitive << ( man_V_11_fu_194_p2 );

    SC_METHOD(thread_mul_ln1192_fu_526_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( z_r_old_V_reg_111 );

    SC_METHOD(thread_mul_ln1192_fu_526_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln1118_fu_487_p1 );

    SC_METHOD(thread_mul_ln1192_fu_526_p2);
    sensitive << ( mul_ln1192_fu_526_p0 );
    sensitive << ( mul_ln1192_fu_526_p1 );

    SC_METHOD(thread_mul_ln1193_fu_502_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( z_i_old_V_reg_99 );

    SC_METHOD(thread_mul_ln1193_fu_502_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( sext_ln1118_fu_487_p1 );

    SC_METHOD(thread_mul_ln1193_fu_502_p2);
    sensitive << ( mul_ln1193_fu_502_p0 );
    sensitive << ( mul_ln1193_fu_502_p1 );

    SC_METHOD(thread_n_fu_444_p2);
    sensitive << ( ush_reg_133 );

    SC_METHOD(thread_or_ln581_fu_345_p2);
    sensitive << ( icmp_ln581_reg_637 );
    sensitive << ( or_ln582_fu_312_p2 );

    SC_METHOD(thread_or_ln582_fu_312_p2);
    sensitive << ( icmp_ln571_reg_631 );
    sensitive << ( icmp_ln582_reg_650 );

    SC_METHOD(thread_or_ln603_5_fu_375_p2);
    sensitive << ( and_ln585_fu_327_p2 );
    sensitive << ( and_ln582_fu_307_p2 );

    SC_METHOD(thread_or_ln603_6_fu_381_p2);
    sensitive << ( or_ln603_fu_362_p2 );
    sensitive << ( or_ln603_5_fu_375_p2 );

    SC_METHOD(thread_or_ln603_fu_362_p2);
    sensitive << ( and_ln603_fu_356_p2 );
    sensitive << ( and_ln585_7_fu_339_p2 );

    SC_METHOD(thread_p_Result_84_fu_190_p1);
    sensitive << ( tmp_fu_182_p3 );

    SC_METHOD(thread_p_Result_s_fu_156_p3);
    sensitive << ( ireg_V_fu_148_p1 );

    SC_METHOD(thread_phi_V_fu_556_p3);
    sensitive << ( tmp_57_fu_461_p3 );
    sensitive << ( add_ln703_fu_538_p2 );
    sensitive << ( sub_ln703_fu_481_p2 );

    SC_METHOD(thread_r_V_fu_455_p2);
    sensitive << ( zext_ln99_fu_434_p1 );

    SC_METHOD(thread_ret_V_6_fu_532_p2);
    sensitive << ( lhs_V_4_fu_518_p3 );
    sensitive << ( mul_ln1192_fu_526_p2 );

    SC_METHOD(thread_ret_V_7_fu_544_p2);
    sensitive << ( lhs_V_fu_494_p3 );
    sensitive << ( mul_ln1193_fu_502_p2 );

    SC_METHOD(thread_ret_V_8_fu_550_p2);
    sensitive << ( lhs_V_4_fu_518_p3 );
    sensitive << ( mul_ln1192_fu_526_p2 );

    SC_METHOD(thread_ret_V_fu_508_p2);
    sensitive << ( lhs_V_fu_494_p3 );
    sensitive << ( mul_ln1193_fu_502_p2 );

    SC_METHOD(thread_select_ln588_fu_401_p3);
    sensitive << ( tmp_56_fu_393_p3 );

    SC_METHOD(thread_select_ln603_7_fu_368_p3);
    sensitive << ( trunc_ln583_reg_656 );
    sensitive << ( and_ln585_fu_327_p2 );
    sensitive << ( trunc_ln586_fu_298_p1 );

    SC_METHOD(thread_select_ln603_8_fu_421_p3);
    sensitive << ( or_ln603_reg_672 );
    sensitive << ( select_ln603_7_reg_677 );
    sensitive << ( select_ln603_fu_414_p3 );

    SC_METHOD(thread_select_ln603_9_fu_427_p3);
    sensitive << ( or_ln603_6_reg_682 );
    sensitive << ( select_ln603_8_fu_421_p3 );

    SC_METHOD(thread_select_ln603_fu_414_p3);
    sensitive << ( and_ln603_reg_667 );
    sensitive << ( shl_ln604_fu_409_p2 );
    sensitive << ( select_ln588_fu_401_p3 );

    SC_METHOD(thread_sext_ln1118_fu_487_p1);
    sensitive << ( r_V_reg_705 );

    SC_METHOD(thread_sext_ln581_fu_276_p1);
    sensitive << ( sh_amt_reg_643 );

    SC_METHOD(thread_sh_amt_fu_248_p3);
    sensitive << ( icmp_ln581_fu_230_p2 );
    sensitive << ( add_ln581_fu_236_p2 );
    sensitive << ( sub_ln581_fu_242_p2 );

    SC_METHOD(thread_shl_ln604_fu_409_p2);
    sensitive << ( trunc_ln583_reg_656 );
    sensitive << ( trunc_ln581_fu_387_p1 );

    SC_METHOD(thread_shl_ln_fu_469_p3);
    sensitive << ( arctan_V232_q0 );

    SC_METHOD(thread_sub_ln581_fu_242_p2);
    sensitive << ( F2_fu_214_p2 );

    SC_METHOD(thread_sub_ln703_fu_481_p2);
    sensitive << ( p_Val2_75_reg_123 );
    sensitive << ( zext_ln703_fu_477_p1 );

    SC_METHOD(thread_tmp_12_fu_574_p4);
    sensitive << ( ret_V_7_fu_544_p2 );

    SC_METHOD(thread_tmp_13_fu_592_p4);
    sensitive << ( ret_V_6_fu_532_p2 );

    SC_METHOD(thread_tmp_14_fu_602_p4);
    sensitive << ( ret_V_8_fu_550_p2 );

    SC_METHOD(thread_tmp_54_fu_220_p4);
    sensitive << ( F2_fu_214_p2 );

    SC_METHOD(thread_tmp_56_fu_393_p3);
    sensitive << ( bitcast_ln696_fu_390_p1 );

    SC_METHOD(thread_tmp_57_fu_461_p3);
    sensitive << ( p_Val2_75_reg_123 );

    SC_METHOD(thread_tmp_fu_182_p3);
    sensitive << ( trunc_ln565_fu_178_p1 );

    SC_METHOD(thread_tmp_s_fu_564_p4);
    sensitive << ( ret_V_fu_508_p2 );

    SC_METHOD(thread_trunc_ln556_fu_152_p1);
    sensitive << ( ireg_V_fu_148_p1 );

    SC_METHOD(thread_trunc_ln565_fu_178_p1);
    sensitive << ( ireg_V_fu_148_p1 );

    SC_METHOD(thread_trunc_ln581_fu_387_p1);
    sensitive << ( sh_amt_reg_643 );

    SC_METHOD(thread_trunc_ln583_fu_262_p1);
    sensitive << ( man_V_12_fu_200_p3 );

    SC_METHOD(thread_trunc_ln586_fu_298_p1);
    sensitive << ( ashr_ln586_fu_293_p2 );

    SC_METHOD(thread_xor_ln571_fu_302_p2);
    sensitive << ( icmp_ln571_reg_631 );

    SC_METHOD(thread_xor_ln581_fu_350_p2);
    sensitive << ( or_ln581_fu_345_p2 );

    SC_METHOD(thread_xor_ln582_fu_316_p2);
    sensitive << ( or_ln582_fu_312_p2 );

    SC_METHOD(thread_xor_ln585_fu_333_p2);
    sensitive << ( icmp_ln585_fu_279_p2 );

    SC_METHOD(thread_z_i_V_fu_612_p3);
    sensitive << ( tmp_57_fu_461_p3 );
    sensitive << ( tmp_14_fu_602_p4 );
    sensitive << ( tmp_13_fu_592_p4 );

    SC_METHOD(thread_z_r_V_fu_584_p3);
    sensitive << ( tmp_57_fu_461_p3 );
    sensitive << ( tmp_12_fu_574_p4 );
    sensitive << ( tmp_s_fu_564_p4 );

    SC_METHOD(thread_zext_ln100_fu_450_p1);
    sensitive << ( ush_reg_133 );

    SC_METHOD(thread_zext_ln461_fu_174_p1);
    sensitive << ( exp_tmp_V_fu_164_p4 );

    SC_METHOD(thread_zext_ln586_fu_289_p1);
    sensitive << ( sext_ln581_fu_276_p1 );

    SC_METHOD(thread_zext_ln703_fu_477_p1);
    sensitive << ( shl_ln_fu_469_p3 );

    SC_METHOD(thread_zext_ln99_fu_434_p1);
    sensitive << ( ush_reg_133 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln99_fu_438_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000001";
    ap_return_preg = "00000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cordicSin_fix_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, arctan_V232_address0, "arctan_V232_address0");
    sc_trace(mVcdFile, arctan_V232_ce0, "arctan_V232_ce0");
    sc_trace(mVcdFile, arctan_V232_q0, "arctan_V232_q0");
    sc_trace(mVcdFile, man_V_12_fu_200_p3, "man_V_12_fu_200_p3");
    sc_trace(mVcdFile, man_V_12_reg_626, "man_V_12_reg_626");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln571_fu_208_p2, "icmp_ln571_fu_208_p2");
    sc_trace(mVcdFile, icmp_ln571_reg_631, "icmp_ln571_reg_631");
    sc_trace(mVcdFile, icmp_ln581_fu_230_p2, "icmp_ln581_fu_230_p2");
    sc_trace(mVcdFile, icmp_ln581_reg_637, "icmp_ln581_reg_637");
    sc_trace(mVcdFile, sh_amt_fu_248_p3, "sh_amt_fu_248_p3");
    sc_trace(mVcdFile, sh_amt_reg_643, "sh_amt_reg_643");
    sc_trace(mVcdFile, icmp_ln582_fu_256_p2, "icmp_ln582_fu_256_p2");
    sc_trace(mVcdFile, icmp_ln582_reg_650, "icmp_ln582_reg_650");
    sc_trace(mVcdFile, trunc_ln583_fu_262_p1, "trunc_ln583_fu_262_p1");
    sc_trace(mVcdFile, trunc_ln583_reg_656, "trunc_ln583_reg_656");
    sc_trace(mVcdFile, tmp_55_reg_662, "tmp_55_reg_662");
    sc_trace(mVcdFile, and_ln603_fu_356_p2, "and_ln603_fu_356_p2");
    sc_trace(mVcdFile, and_ln603_reg_667, "and_ln603_reg_667");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, or_ln603_fu_362_p2, "or_ln603_fu_362_p2");
    sc_trace(mVcdFile, or_ln603_reg_672, "or_ln603_reg_672");
    sc_trace(mVcdFile, select_ln603_7_fu_368_p3, "select_ln603_7_fu_368_p3");
    sc_trace(mVcdFile, select_ln603_7_reg_677, "select_ln603_7_reg_677");
    sc_trace(mVcdFile, or_ln603_6_fu_381_p2, "or_ln603_6_fu_381_p2");
    sc_trace(mVcdFile, or_ln603_6_reg_682, "or_ln603_6_reg_682");
    sc_trace(mVcdFile, select_ln603_9_fu_427_p3, "select_ln603_9_fu_427_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, n_fu_444_p2, "n_fu_444_p2");
    sc_trace(mVcdFile, n_reg_695, "n_reg_695");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln99_fu_438_p2, "icmp_ln99_fu_438_p2");
    sc_trace(mVcdFile, r_V_fu_455_p2, "r_V_fu_455_p2");
    sc_trace(mVcdFile, r_V_reg_705, "r_V_reg_705");
    sc_trace(mVcdFile, phi_V_fu_556_p3, "phi_V_fu_556_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, z_r_V_fu_584_p3, "z_r_V_fu_584_p3");
    sc_trace(mVcdFile, z_i_V_fu_612_p3, "z_i_V_fu_612_p3");
    sc_trace(mVcdFile, z_i_old_V_reg_99, "z_i_old_V_reg_99");
    sc_trace(mVcdFile, z_r_old_V_reg_111, "z_r_old_V_reg_111");
    sc_trace(mVcdFile, p_Val2_75_reg_123, "p_Val2_75_reg_123");
    sc_trace(mVcdFile, ush_reg_133, "ush_reg_133");
    sc_trace(mVcdFile, zext_ln100_fu_450_p1, "zext_ln100_fu_450_p1");
    sc_trace(mVcdFile, grp_fu_144_p1, "grp_fu_144_p1");
    sc_trace(mVcdFile, ireg_V_fu_148_p1, "ireg_V_fu_148_p1");
    sc_trace(mVcdFile, exp_tmp_V_fu_164_p4, "exp_tmp_V_fu_164_p4");
    sc_trace(mVcdFile, trunc_ln565_fu_178_p1, "trunc_ln565_fu_178_p1");
    sc_trace(mVcdFile, tmp_fu_182_p3, "tmp_fu_182_p3");
    sc_trace(mVcdFile, p_Result_84_fu_190_p1, "p_Result_84_fu_190_p1");
    sc_trace(mVcdFile, p_Result_s_fu_156_p3, "p_Result_s_fu_156_p3");
    sc_trace(mVcdFile, man_V_11_fu_194_p2, "man_V_11_fu_194_p2");
    sc_trace(mVcdFile, trunc_ln556_fu_152_p1, "trunc_ln556_fu_152_p1");
    sc_trace(mVcdFile, zext_ln461_fu_174_p1, "zext_ln461_fu_174_p1");
    sc_trace(mVcdFile, F2_fu_214_p2, "F2_fu_214_p2");
    sc_trace(mVcdFile, tmp_54_fu_220_p4, "tmp_54_fu_220_p4");
    sc_trace(mVcdFile, add_ln581_fu_236_p2, "add_ln581_fu_236_p2");
    sc_trace(mVcdFile, sub_ln581_fu_242_p2, "sub_ln581_fu_242_p2");
    sc_trace(mVcdFile, sext_ln581_fu_276_p1, "sext_ln581_fu_276_p1");
    sc_trace(mVcdFile, zext_ln586_fu_289_p1, "zext_ln586_fu_289_p1");
    sc_trace(mVcdFile, ashr_ln586_fu_293_p2, "ashr_ln586_fu_293_p2");
    sc_trace(mVcdFile, xor_ln571_fu_302_p2, "xor_ln571_fu_302_p2");
    sc_trace(mVcdFile, or_ln582_fu_312_p2, "or_ln582_fu_312_p2");
    sc_trace(mVcdFile, xor_ln582_fu_316_p2, "xor_ln582_fu_316_p2");
    sc_trace(mVcdFile, and_ln581_fu_322_p2, "and_ln581_fu_322_p2");
    sc_trace(mVcdFile, icmp_ln585_fu_279_p2, "icmp_ln585_fu_279_p2");
    sc_trace(mVcdFile, xor_ln585_fu_333_p2, "xor_ln585_fu_333_p2");
    sc_trace(mVcdFile, or_ln581_fu_345_p2, "or_ln581_fu_345_p2");
    sc_trace(mVcdFile, icmp_ln603_fu_284_p2, "icmp_ln603_fu_284_p2");
    sc_trace(mVcdFile, xor_ln581_fu_350_p2, "xor_ln581_fu_350_p2");
    sc_trace(mVcdFile, and_ln585_7_fu_339_p2, "and_ln585_7_fu_339_p2");
    sc_trace(mVcdFile, and_ln585_fu_327_p2, "and_ln585_fu_327_p2");
    sc_trace(mVcdFile, trunc_ln586_fu_298_p1, "trunc_ln586_fu_298_p1");
    sc_trace(mVcdFile, and_ln582_fu_307_p2, "and_ln582_fu_307_p2");
    sc_trace(mVcdFile, or_ln603_5_fu_375_p2, "or_ln603_5_fu_375_p2");
    sc_trace(mVcdFile, bitcast_ln696_fu_390_p1, "bitcast_ln696_fu_390_p1");
    sc_trace(mVcdFile, tmp_56_fu_393_p3, "tmp_56_fu_393_p3");
    sc_trace(mVcdFile, trunc_ln581_fu_387_p1, "trunc_ln581_fu_387_p1");
    sc_trace(mVcdFile, shl_ln604_fu_409_p2, "shl_ln604_fu_409_p2");
    sc_trace(mVcdFile, select_ln588_fu_401_p3, "select_ln588_fu_401_p3");
    sc_trace(mVcdFile, select_ln603_fu_414_p3, "select_ln603_fu_414_p3");
    sc_trace(mVcdFile, select_ln603_8_fu_421_p3, "select_ln603_8_fu_421_p3");
    sc_trace(mVcdFile, zext_ln99_fu_434_p1, "zext_ln99_fu_434_p1");
    sc_trace(mVcdFile, shl_ln_fu_469_p3, "shl_ln_fu_469_p3");
    sc_trace(mVcdFile, zext_ln703_fu_477_p1, "zext_ln703_fu_477_p1");
    sc_trace(mVcdFile, mul_ln1193_fu_502_p0, "mul_ln1193_fu_502_p0");
    sc_trace(mVcdFile, mul_ln1193_fu_502_p1, "mul_ln1193_fu_502_p1");
    sc_trace(mVcdFile, sext_ln1118_fu_487_p1, "sext_ln1118_fu_487_p1");
    sc_trace(mVcdFile, lhs_V_fu_494_p3, "lhs_V_fu_494_p3");
    sc_trace(mVcdFile, mul_ln1193_fu_502_p2, "mul_ln1193_fu_502_p2");
    sc_trace(mVcdFile, mul_ln1192_fu_526_p0, "mul_ln1192_fu_526_p0");
    sc_trace(mVcdFile, mul_ln1192_fu_526_p1, "mul_ln1192_fu_526_p1");
    sc_trace(mVcdFile, lhs_V_4_fu_518_p3, "lhs_V_4_fu_518_p3");
    sc_trace(mVcdFile, mul_ln1192_fu_526_p2, "mul_ln1192_fu_526_p2");
    sc_trace(mVcdFile, tmp_57_fu_461_p3, "tmp_57_fu_461_p3");
    sc_trace(mVcdFile, add_ln703_fu_538_p2, "add_ln703_fu_538_p2");
    sc_trace(mVcdFile, sub_ln703_fu_481_p2, "sub_ln703_fu_481_p2");
    sc_trace(mVcdFile, ret_V_fu_508_p2, "ret_V_fu_508_p2");
    sc_trace(mVcdFile, ret_V_7_fu_544_p2, "ret_V_7_fu_544_p2");
    sc_trace(mVcdFile, tmp_12_fu_574_p4, "tmp_12_fu_574_p4");
    sc_trace(mVcdFile, tmp_s_fu_564_p4, "tmp_s_fu_564_p4");
    sc_trace(mVcdFile, ret_V_6_fu_532_p2, "ret_V_6_fu_532_p2");
    sc_trace(mVcdFile, ret_V_8_fu_550_p2, "ret_V_8_fu_550_p2");
    sc_trace(mVcdFile, tmp_14_fu_602_p4, "tmp_14_fu_602_p4");
    sc_trace(mVcdFile, tmp_13_fu_592_p4, "tmp_13_fu_592_p4");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

cordicSin_fix::~cordicSin_fix() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete arctan_V232_U;
    delete top_level2_fpext_lbW_U63;
}

void cordicSin_fix::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void cordicSin_fix::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_438_p2.read(), ap_const_lv1_1))) {
            ap_return_preg = z_i_old_V_reg_99.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_Val2_75_reg_123 = select_ln603_9_fu_427_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_Val2_75_reg_123 = phi_V_fu_556_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ush_reg_133 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ush_reg_133 = n_reg_695.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        z_i_old_V_reg_99 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        z_i_old_V_reg_99 = z_i_V_fu_612_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        z_r_old_V_reg_111 = ap_const_lv8_4D;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        z_r_old_V_reg_111 = z_r_V_fu_584_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        and_ln603_reg_667 = and_ln603_fu_356_p2.read();
        or_ln603_6_reg_682 = or_ln603_6_fu_381_p2.read();
        or_ln603_reg_672 = or_ln603_fu_362_p2.read();
        select_ln603_7_reg_677 = select_ln603_7_fu_368_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        icmp_ln571_reg_631 = icmp_ln571_fu_208_p2.read();
        icmp_ln581_reg_637 = icmp_ln581_fu_230_p2.read();
        icmp_ln582_reg_650 = icmp_ln582_fu_256_p2.read();
        man_V_12_reg_626 = man_V_12_fu_200_p3.read();
        sh_amt_reg_643 = sh_amt_fu_248_p3.read();
        tmp_55_reg_662 = sh_amt_fu_248_p3.read().range(11, 3);
        trunc_ln583_reg_656 = trunc_ln583_fu_262_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        n_reg_695 = n_fu_444_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln99_fu_438_p2.read(), ap_const_lv1_0))) {
        r_V_reg_705 = r_V_fu_455_p2.read();
    }
}

void cordicSin_fix::thread_F2_fu_214_p2() {
    F2_fu_214_p2 = (!ap_const_lv12_433.is_01() || !zext_ln461_fu_174_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_433) - sc_biguint<12>(zext_ln461_fu_174_p1.read()));
}

void cordicSin_fix::thread_add_ln581_fu_236_p2() {
    add_ln581_fu_236_p2 = (!ap_const_lv12_FF9.is_01() || !F2_fu_214_p2.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FF9) + sc_biguint<12>(F2_fu_214_p2.read()));
}

void cordicSin_fix::thread_add_ln703_fu_538_p2() {
    add_ln703_fu_538_p2 = (!p_Val2_75_reg_123.read().is_01() || !zext_ln703_fu_477_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_75_reg_123.read()) + sc_biguint<8>(zext_ln703_fu_477_p1.read()));
}

void cordicSin_fix::thread_and_ln581_fu_322_p2() {
    and_ln581_fu_322_p2 = (icmp_ln581_reg_637.read() & xor_ln582_fu_316_p2.read());
}

void cordicSin_fix::thread_and_ln582_fu_307_p2() {
    and_ln582_fu_307_p2 = (icmp_ln582_reg_650.read() & xor_ln571_fu_302_p2.read());
}

void cordicSin_fix::thread_and_ln585_7_fu_339_p2() {
    and_ln585_7_fu_339_p2 = (and_ln581_fu_322_p2.read() & xor_ln585_fu_333_p2.read());
}

void cordicSin_fix::thread_and_ln585_fu_327_p2() {
    and_ln585_fu_327_p2 = (and_ln581_fu_322_p2.read() & icmp_ln585_fu_279_p2.read());
}

void cordicSin_fix::thread_and_ln603_fu_356_p2() {
    and_ln603_fu_356_p2 = (icmp_ln603_fu_284_p2.read() & xor_ln581_fu_350_p2.read());
}

void cordicSin_fix::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cordicSin_fix::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cordicSin_fix::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cordicSin_fix::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void cordicSin_fix::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void cordicSin_fix::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void cordicSin_fix::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(icmp_ln99_fu_438_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cordicSin_fix::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cordicSin_fix::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln99_fu_438_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cordicSin_fix::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln99_fu_438_p2.read(), ap_const_lv1_1))) {
        ap_return = z_i_old_V_reg_99.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void cordicSin_fix::thread_arctan_V232_address0() {
    arctan_V232_address0 =  (sc_lv<6>) (zext_ln100_fu_450_p1.read());
}

void cordicSin_fix::thread_arctan_V232_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        arctan_V232_ce0 = ap_const_logic_1;
    } else {
        arctan_V232_ce0 = ap_const_logic_0;
    }
}

void cordicSin_fix::thread_ashr_ln586_fu_293_p2() {
    ashr_ln586_fu_293_p2 = (!man_V_12_reg_626.read().is_01() || !zext_ln586_fu_289_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(man_V_12_reg_626.read()) >> (unsigned short)zext_ln586_fu_289_p1.read().to_uint();
}

void cordicSin_fix::thread_bitcast_ln696_fu_390_p1() {
    bitcast_ln696_fu_390_p1 = x.read();
}

void cordicSin_fix::thread_exp_tmp_V_fu_164_p4() {
    exp_tmp_V_fu_164_p4 = ireg_V_fu_148_p1.read().range(62, 52);
}

void cordicSin_fix::thread_icmp_ln571_fu_208_p2() {
    icmp_ln571_fu_208_p2 = (!trunc_ln556_fu_152_p1.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln556_fu_152_p1.read() == ap_const_lv63_0);
}

void cordicSin_fix::thread_icmp_ln581_fu_230_p2() {
    icmp_ln581_fu_230_p2 = (!tmp_54_fu_220_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): (sc_bigint<9>(tmp_54_fu_220_p4.read()) > sc_bigint<9>(ap_const_lv9_0));
}

void cordicSin_fix::thread_icmp_ln582_fu_256_p2() {
    icmp_ln582_fu_256_p2 = (!F2_fu_214_p2.read().is_01() || !ap_const_lv12_7.is_01())? sc_lv<1>(): sc_lv<1>(F2_fu_214_p2.read() == ap_const_lv12_7);
}

void cordicSin_fix::thread_icmp_ln585_fu_279_p2() {
    icmp_ln585_fu_279_p2 = (!sh_amt_reg_643.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_biguint<12>(sh_amt_reg_643.read()) < sc_biguint<12>(ap_const_lv12_36));
}

void cordicSin_fix::thread_icmp_ln603_fu_284_p2() {
    icmp_ln603_fu_284_p2 = (!tmp_55_reg_662.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_55_reg_662.read() == ap_const_lv9_0);
}

void cordicSin_fix::thread_icmp_ln99_fu_438_p2() {
    icmp_ln99_fu_438_p2 = (!ush_reg_133.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(ush_reg_133.read() == ap_const_lv4_A);
}

void cordicSin_fix::thread_ireg_V_fu_148_p1() {
    ireg_V_fu_148_p1 = grp_fu_144_p1.read();
}

void cordicSin_fix::thread_lhs_V_4_fu_518_p3() {
    lhs_V_4_fu_518_p3 = esl_concat<8,7>(z_i_old_V_reg_99.read(), ap_const_lv7_0);
}

void cordicSin_fix::thread_lhs_V_fu_494_p3() {
    lhs_V_fu_494_p3 = esl_concat<8,7>(z_r_old_V_reg_111.read(), ap_const_lv7_0);
}

void cordicSin_fix::thread_man_V_11_fu_194_p2() {
    man_V_11_fu_194_p2 = (!ap_const_lv54_0.is_01() || !p_Result_84_fu_190_p1.read().is_01())? sc_lv<54>(): (sc_biguint<54>(ap_const_lv54_0) - sc_biguint<54>(p_Result_84_fu_190_p1.read()));
}

void cordicSin_fix::thread_man_V_12_fu_200_p3() {
    man_V_12_fu_200_p3 = (!p_Result_s_fu_156_p3.read()[0].is_01())? sc_lv<54>(): ((p_Result_s_fu_156_p3.read()[0].to_bool())? man_V_11_fu_194_p2.read(): p_Result_84_fu_190_p1.read());
}

void cordicSin_fix::thread_mul_ln1192_fu_526_p0() {
    mul_ln1192_fu_526_p0 = z_r_old_V_reg_111.read();
}

void cordicSin_fix::thread_mul_ln1192_fu_526_p1() {
    mul_ln1192_fu_526_p1 =  (sc_lv<8>) (sext_ln1118_fu_487_p1.read());
}

void cordicSin_fix::thread_mul_ln1192_fu_526_p2() {
    mul_ln1192_fu_526_p2 = (!mul_ln1192_fu_526_p0.read().is_01() || !mul_ln1192_fu_526_p1.read().is_01())? sc_lv<15>(): sc_bigint<8>(mul_ln1192_fu_526_p0.read()) * sc_bigint<8>(mul_ln1192_fu_526_p1.read());
}

void cordicSin_fix::thread_mul_ln1193_fu_502_p0() {
    mul_ln1193_fu_502_p0 = z_i_old_V_reg_99.read();
}

void cordicSin_fix::thread_mul_ln1193_fu_502_p1() {
    mul_ln1193_fu_502_p1 =  (sc_lv<8>) (sext_ln1118_fu_487_p1.read());
}

void cordicSin_fix::thread_mul_ln1193_fu_502_p2() {
    mul_ln1193_fu_502_p2 = (!mul_ln1193_fu_502_p0.read().is_01() || !mul_ln1193_fu_502_p1.read().is_01())? sc_lv<15>(): sc_bigint<8>(mul_ln1193_fu_502_p0.read()) * sc_bigint<8>(mul_ln1193_fu_502_p1.read());
}

void cordicSin_fix::thread_n_fu_444_p2() {
    n_fu_444_p2 = (!ush_reg_133.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ush_reg_133.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void cordicSin_fix::thread_or_ln581_fu_345_p2() {
    or_ln581_fu_345_p2 = (or_ln582_fu_312_p2.read() | icmp_ln581_reg_637.read());
}

void cordicSin_fix::thread_or_ln582_fu_312_p2() {
    or_ln582_fu_312_p2 = (icmp_ln571_reg_631.read() | icmp_ln582_reg_650.read());
}

void cordicSin_fix::thread_or_ln603_5_fu_375_p2() {
    or_ln603_5_fu_375_p2 = (and_ln585_fu_327_p2.read() | and_ln582_fu_307_p2.read());
}

void cordicSin_fix::thread_or_ln603_6_fu_381_p2() {
    or_ln603_6_fu_381_p2 = (or_ln603_fu_362_p2.read() | or_ln603_5_fu_375_p2.read());
}

void cordicSin_fix::thread_or_ln603_fu_362_p2() {
    or_ln603_fu_362_p2 = (and_ln603_fu_356_p2.read() | and_ln585_7_fu_339_p2.read());
}

void cordicSin_fix::thread_p_Result_84_fu_190_p1() {
    p_Result_84_fu_190_p1 = esl_zext<54,53>(tmp_fu_182_p3.read());
}

void cordicSin_fix::thread_p_Result_s_fu_156_p3() {
    p_Result_s_fu_156_p3 = ireg_V_fu_148_p1.read().range(63, 63);
}

void cordicSin_fix::thread_phi_V_fu_556_p3() {
    phi_V_fu_556_p3 = (!tmp_57_fu_461_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_57_fu_461_p3.read()[0].to_bool())? add_ln703_fu_538_p2.read(): sub_ln703_fu_481_p2.read());
}

void cordicSin_fix::thread_r_V_fu_455_p2() {
    r_V_fu_455_p2 = (!ap_const_lv8_80.is_01() || !zext_ln99_fu_434_p1.read().is_01())? sc_lv<8>(): sc_bigint<8>(ap_const_lv8_80) >> (unsigned short)zext_ln99_fu_434_p1.read().to_uint();
}

void cordicSin_fix::thread_ret_V_6_fu_532_p2() {
    ret_V_6_fu_532_p2 = (!lhs_V_4_fu_518_p3.read().is_01() || !mul_ln1192_fu_526_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(lhs_V_4_fu_518_p3.read()) + sc_biguint<15>(mul_ln1192_fu_526_p2.read()));
}

void cordicSin_fix::thread_ret_V_7_fu_544_p2() {
    ret_V_7_fu_544_p2 = (!mul_ln1193_fu_502_p2.read().is_01() || !lhs_V_fu_494_p3.read().is_01())? sc_lv<15>(): (sc_biguint<15>(mul_ln1193_fu_502_p2.read()) + sc_biguint<15>(lhs_V_fu_494_p3.read()));
}

void cordicSin_fix::thread_ret_V_8_fu_550_p2() {
    ret_V_8_fu_550_p2 = (!lhs_V_4_fu_518_p3.read().is_01() || !mul_ln1192_fu_526_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(lhs_V_4_fu_518_p3.read()) - sc_biguint<15>(mul_ln1192_fu_526_p2.read()));
}

void cordicSin_fix::thread_ret_V_fu_508_p2() {
    ret_V_fu_508_p2 = (!lhs_V_fu_494_p3.read().is_01() || !mul_ln1193_fu_502_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(lhs_V_fu_494_p3.read()) - sc_biguint<15>(mul_ln1193_fu_502_p2.read()));
}

void cordicSin_fix::thread_select_ln588_fu_401_p3() {
    select_ln588_fu_401_p3 = (!tmp_56_fu_393_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_56_fu_393_p3.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void cordicSin_fix::thread_select_ln603_7_fu_368_p3() {
    select_ln603_7_fu_368_p3 = (!and_ln585_fu_327_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln585_fu_327_p2.read()[0].to_bool())? trunc_ln586_fu_298_p1.read(): trunc_ln583_reg_656.read());
}

void cordicSin_fix::thread_select_ln603_8_fu_421_p3() {
    select_ln603_8_fu_421_p3 = (!or_ln603_reg_672.read()[0].is_01())? sc_lv<8>(): ((or_ln603_reg_672.read()[0].to_bool())? select_ln603_fu_414_p3.read(): select_ln603_7_reg_677.read());
}

void cordicSin_fix::thread_select_ln603_9_fu_427_p3() {
    select_ln603_9_fu_427_p3 = (!or_ln603_6_reg_682.read()[0].is_01())? sc_lv<8>(): ((or_ln603_6_reg_682.read()[0].to_bool())? select_ln603_8_fu_421_p3.read(): ap_const_lv8_0);
}

void cordicSin_fix::thread_select_ln603_fu_414_p3() {
    select_ln603_fu_414_p3 = (!and_ln603_reg_667.read()[0].is_01())? sc_lv<8>(): ((and_ln603_reg_667.read()[0].to_bool())? shl_ln604_fu_409_p2.read(): select_ln588_fu_401_p3.read());
}

void cordicSin_fix::thread_sext_ln1118_fu_487_p1() {
    sext_ln1118_fu_487_p1 = esl_sext<15,8>(r_V_reg_705.read());
}

void cordicSin_fix::thread_sext_ln581_fu_276_p1() {
    sext_ln581_fu_276_p1 = esl_sext<32,12>(sh_amt_reg_643.read());
}

void cordicSin_fix::thread_sh_amt_fu_248_p3() {
    sh_amt_fu_248_p3 = (!icmp_ln581_fu_230_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln581_fu_230_p2.read()[0].to_bool())? add_ln581_fu_236_p2.read(): sub_ln581_fu_242_p2.read());
}

void cordicSin_fix::thread_shl_ln604_fu_409_p2() {
    shl_ln604_fu_409_p2 = (!trunc_ln581_fu_387_p1.read().is_01())? sc_lv<8>(): trunc_ln583_reg_656.read() << (unsigned short)trunc_ln581_fu_387_p1.read().to_uint();
}

void cordicSin_fix::thread_shl_ln_fu_469_p3() {
    shl_ln_fu_469_p3 = esl_concat<4,3>(arctan_V232_q0.read(), ap_const_lv3_0);
}

void cordicSin_fix::thread_sub_ln581_fu_242_p2() {
    sub_ln581_fu_242_p2 = (!ap_const_lv12_7.is_01() || !F2_fu_214_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_7) - sc_biguint<12>(F2_fu_214_p2.read()));
}

void cordicSin_fix::thread_sub_ln703_fu_481_p2() {
    sub_ln703_fu_481_p2 = (!p_Val2_75_reg_123.read().is_01() || !zext_ln703_fu_477_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_75_reg_123.read()) - sc_biguint<8>(zext_ln703_fu_477_p1.read()));
}

void cordicSin_fix::thread_tmp_12_fu_574_p4() {
    tmp_12_fu_574_p4 = ret_V_7_fu_544_p2.read().range(14, 7);
}

void cordicSin_fix::thread_tmp_13_fu_592_p4() {
    tmp_13_fu_592_p4 = ret_V_6_fu_532_p2.read().range(14, 7);
}

void cordicSin_fix::thread_tmp_14_fu_602_p4() {
    tmp_14_fu_602_p4 = ret_V_8_fu_550_p2.read().range(14, 7);
}

void cordicSin_fix::thread_tmp_54_fu_220_p4() {
    tmp_54_fu_220_p4 = F2_fu_214_p2.read().range(11, 3);
}

void cordicSin_fix::thread_tmp_56_fu_393_p3() {
    tmp_56_fu_393_p3 = bitcast_ln696_fu_390_p1.read().range(31, 31);
}

void cordicSin_fix::thread_tmp_57_fu_461_p3() {
    tmp_57_fu_461_p3 = p_Val2_75_reg_123.read().range(7, 7);
}

void cordicSin_fix::thread_tmp_fu_182_p3() {
    tmp_fu_182_p3 = esl_concat<1,52>(ap_const_lv1_1, trunc_ln565_fu_178_p1.read());
}

void cordicSin_fix::thread_tmp_s_fu_564_p4() {
    tmp_s_fu_564_p4 = ret_V_fu_508_p2.read().range(14, 7);
}

void cordicSin_fix::thread_trunc_ln556_fu_152_p1() {
    trunc_ln556_fu_152_p1 = ireg_V_fu_148_p1.read().range(63-1, 0);
}

void cordicSin_fix::thread_trunc_ln565_fu_178_p1() {
    trunc_ln565_fu_178_p1 = ireg_V_fu_148_p1.read().range(52-1, 0);
}

void cordicSin_fix::thread_trunc_ln581_fu_387_p1() {
    trunc_ln581_fu_387_p1 = sh_amt_reg_643.read().range(8-1, 0);
}

void cordicSin_fix::thread_trunc_ln583_fu_262_p1() {
    trunc_ln583_fu_262_p1 = man_V_12_fu_200_p3.read().range(8-1, 0);
}

void cordicSin_fix::thread_trunc_ln586_fu_298_p1() {
    trunc_ln586_fu_298_p1 = ashr_ln586_fu_293_p2.read().range(8-1, 0);
}

void cordicSin_fix::thread_xor_ln571_fu_302_p2() {
    xor_ln571_fu_302_p2 = (icmp_ln571_reg_631.read() ^ ap_const_lv1_1);
}

void cordicSin_fix::thread_xor_ln581_fu_350_p2() {
    xor_ln581_fu_350_p2 = (or_ln581_fu_345_p2.read() ^ ap_const_lv1_1);
}

void cordicSin_fix::thread_xor_ln582_fu_316_p2() {
    xor_ln582_fu_316_p2 = (or_ln582_fu_312_p2.read() ^ ap_const_lv1_1);
}

void cordicSin_fix::thread_xor_ln585_fu_333_p2() {
    xor_ln585_fu_333_p2 = (icmp_ln585_fu_279_p2.read() ^ ap_const_lv1_1);
}

void cordicSin_fix::thread_z_i_V_fu_612_p3() {
    z_i_V_fu_612_p3 = (!tmp_57_fu_461_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_57_fu_461_p3.read()[0].to_bool())? tmp_14_fu_602_p4.read(): tmp_13_fu_592_p4.read());
}

void cordicSin_fix::thread_z_r_V_fu_584_p3() {
    z_r_V_fu_584_p3 = (!tmp_57_fu_461_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_57_fu_461_p3.read()[0].to_bool())? tmp_12_fu_574_p4.read(): tmp_s_fu_564_p4.read());
}

void cordicSin_fix::thread_zext_ln100_fu_450_p1() {
    zext_ln100_fu_450_p1 = esl_zext<64,4>(ush_reg_133.read());
}

void cordicSin_fix::thread_zext_ln461_fu_174_p1() {
    zext_ln461_fu_174_p1 = esl_zext<12,11>(exp_tmp_V_fu_164_p4.read());
}

void cordicSin_fix::thread_zext_ln586_fu_289_p1() {
    zext_ln586_fu_289_p1 = esl_zext<54,32>(sext_ln581_fu_276_p1.read());
}

void cordicSin_fix::thread_zext_ln703_fu_477_p1() {
    zext_ln703_fu_477_p1 = esl_zext<8,7>(shl_ln_fu_469_p3.read());
}

void cordicSin_fix::thread_zext_ln99_fu_434_p1() {
    zext_ln99_fu_434_p1 = esl_zext<8,4>(ush_reg_133.read());
}

void cordicSin_fix::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln99_fu_438_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

}

