// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _cordicCos_fix_HH_
#define _cordicCos_fix_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "top_level_fpext_3lbW.h"
#include "cordicCos_fix_arckbM.h"

namespace ap_rtl {

struct cordicCos_fix : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > x;
    sc_out< sc_lv<8> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    cordicCos_fix(sc_module_name name);
    SC_HAS_PROCESS(cordicCos_fix);

    ~cordicCos_fix();

    sc_trace_file* mVcdFile;

    cordicCos_fix_arckbM* arctan_V_U;
    top_level_fpext_3lbW<1,2,32,64>* top_level_fpext_3lbW_U61;
    sc_signal< sc_lv<6> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<6> > arctan_V_address0;
    sc_signal< sc_logic > arctan_V_ce0;
    sc_signal< sc_lv<6> > arctan_V_q0;
    sc_signal< sc_lv<54> > man_V_4_fu_198_p3;
    sc_signal< sc_lv<54> > man_V_4_reg_606;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln571_fu_206_p2;
    sc_signal< sc_lv<1> > icmp_ln571_reg_611;
    sc_signal< sc_lv<1> > icmp_ln581_fu_218_p2;
    sc_signal< sc_lv<1> > icmp_ln581_reg_617;
    sc_signal< sc_lv<12> > sh_amt_fu_236_p3;
    sc_signal< sc_lv<12> > sh_amt_reg_623;
    sc_signal< sc_lv<1> > icmp_ln582_fu_244_p2;
    sc_signal< sc_lv<1> > icmp_ln582_reg_630;
    sc_signal< sc_lv<8> > trunc_ln583_fu_250_p1;
    sc_signal< sc_lv<8> > trunc_ln583_reg_636;
    sc_signal< sc_lv<9> > tmp_28_reg_642;
    sc_signal< sc_lv<1> > and_ln603_fu_344_p2;
    sc_signal< sc_lv<1> > and_ln603_reg_647;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > or_ln603_fu_350_p2;
    sc_signal< sc_lv<1> > or_ln603_reg_652;
    sc_signal< sc_lv<8> > select_ln603_4_fu_356_p3;
    sc_signal< sc_lv<8> > select_ln603_4_reg_657;
    sc_signal< sc_lv<1> > or_ln603_4_fu_369_p2;
    sc_signal< sc_lv<1> > or_ln603_4_reg_662;
    sc_signal< sc_lv<8> > select_ln603_6_fu_415_p3;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<4> > n_fu_432_p2;
    sc_signal< sc_lv<4> > n_reg_675;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<1> > icmp_ln125_fu_426_p2;
    sc_signal< sc_lv<7> > lshr_ln1333_fu_443_p2;
    sc_signal< sc_lv<7> > lshr_ln1333_reg_685;
    sc_signal< sc_lv<8> > phi_V_fu_536_p3;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<8> > z_r_V_fu_564_p3;
    sc_signal< sc_lv<8> > z_i_V_fu_592_p3;
    sc_signal< sc_lv<8> > z_r_old_V_reg_97;
    sc_signal< sc_lv<8> > p_Val2_30_reg_109;
    sc_signal< sc_lv<8> > z_i_old_V_reg_119;
    sc_signal< sc_lv<4> > ush_reg_131;
    sc_signal< sc_lv<64> > zext_ln126_fu_438_p1;
    sc_signal< sc_lv<64> > grp_fu_142_p1;
    sc_signal< sc_lv<64> > ireg_V_fu_146_p1;
    sc_signal< sc_lv<11> > exp_tmp_V_fu_162_p4;
    sc_signal< sc_lv<52> > trunc_ln565_fu_176_p1;
    sc_signal< sc_lv<53> > tmp_fu_180_p3;
    sc_signal< sc_lv<54> > p_Result_32_fu_188_p1;
    sc_signal< sc_lv<1> > p_Result_s_fu_154_p3;
    sc_signal< sc_lv<54> > man_V_3_fu_192_p2;
    sc_signal< sc_lv<63> > trunc_ln556_fu_150_p1;
    sc_signal< sc_lv<12> > zext_ln461_fu_172_p1;
    sc_signal< sc_lv<12> > F2_fu_212_p2;
    sc_signal< sc_lv<12> > add_ln581_fu_224_p2;
    sc_signal< sc_lv<12> > sub_ln581_fu_230_p2;
    sc_signal< sc_lv<32> > sext_ln581_fu_264_p1;
    sc_signal< sc_lv<54> > zext_ln586_fu_277_p1;
    sc_signal< sc_lv<54> > ashr_ln586_fu_281_p2;
    sc_signal< sc_lv<1> > xor_ln571_fu_290_p2;
    sc_signal< sc_lv<1> > or_ln582_fu_300_p2;
    sc_signal< sc_lv<1> > xor_ln582_fu_304_p2;
    sc_signal< sc_lv<1> > and_ln581_fu_310_p2;
    sc_signal< sc_lv<1> > icmp_ln585_fu_267_p2;
    sc_signal< sc_lv<1> > xor_ln585_fu_321_p2;
    sc_signal< sc_lv<1> > or_ln581_fu_333_p2;
    sc_signal< sc_lv<1> > icmp_ln603_fu_272_p2;
    sc_signal< sc_lv<1> > xor_ln581_fu_338_p2;
    sc_signal< sc_lv<1> > and_ln585_2_fu_327_p2;
    sc_signal< sc_lv<1> > and_ln585_fu_315_p2;
    sc_signal< sc_lv<8> > trunc_ln586_fu_286_p1;
    sc_signal< sc_lv<1> > and_ln582_fu_295_p2;
    sc_signal< sc_lv<1> > or_ln603_3_fu_363_p2;
    sc_signal< sc_lv<32> > bitcast_ln696_fu_378_p1;
    sc_signal< sc_lv<1> > tmp_29_fu_381_p3;
    sc_signal< sc_lv<8> > trunc_ln581_fu_375_p1;
    sc_signal< sc_lv<8> > shl_ln604_fu_397_p2;
    sc_signal< sc_lv<8> > select_ln588_fu_389_p3;
    sc_signal< sc_lv<8> > select_ln603_fu_402_p3;
    sc_signal< sc_lv<8> > select_ln603_5_fu_409_p3;
    sc_signal< sc_lv<7> > zext_ln125_fu_422_p1;
    sc_signal< sc_lv<8> > zext_ln126_1_fu_449_p1;
    sc_signal< sc_lv<8> > mul_ln1193_fu_482_p0;
    sc_signal< sc_lv<7> > mul_ln1193_fu_482_p1;
    sc_signal< sc_lv<14> > zext_ln1118_fu_467_p1;
    sc_signal< sc_lv<14> > lhs_V_fu_474_p3;
    sc_signal< sc_lv<14> > mul_ln1193_fu_482_p2;
    sc_signal< sc_lv<7> > mul_ln703_fu_506_p0;
    sc_signal< sc_lv<8> > mul_ln703_fu_506_p1;
    sc_signal< sc_lv<14> > lhs_V_2_fu_498_p3;
    sc_signal< sc_lv<14> > mul_ln703_fu_506_p2;
    sc_signal< sc_lv<1> > tmp_30_fu_453_p3;
    sc_signal< sc_lv<8> > add_ln703_fu_518_p2;
    sc_signal< sc_lv<8> > sub_ln703_fu_461_p2;
    sc_signal< sc_lv<14> > ret_V_fu_488_p2;
    sc_signal< sc_lv<14> > ret_V_5_fu_524_p2;
    sc_signal< sc_lv<8> > tmp_10_fu_554_p4;
    sc_signal< sc_lv<8> > tmp_s_fu_544_p4;
    sc_signal< sc_lv<14> > ret_V_4_fu_512_p2;
    sc_signal< sc_lv<14> > ret_V_6_fu_530_p2;
    sc_signal< sc_lv<8> > tmp_12_fu_582_p4;
    sc_signal< sc_lv<8> > tmp_11_fu_572_p4;
    sc_signal< sc_lv<8> > ap_return_preg;
    sc_signal< sc_lv<6> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<6> ap_ST_fsm_state1;
    static const sc_lv<6> ap_ST_fsm_state2;
    static const sc_lv<6> ap_ST_fsm_state3;
    static const sc_lv<6> ap_ST_fsm_state4;
    static const sc_lv<6> ap_ST_fsm_state5;
    static const sc_lv<6> ap_ST_fsm_state6;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<8> ap_const_lv8_26;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<54> ap_const_lv54_0;
    static const sc_lv<63> ap_const_lv63_0;
    static const sc_lv<12> ap_const_lv12_433;
    static const sc_lv<12> ap_const_lv12_6;
    static const sc_lv<12> ap_const_lv12_FFA;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<12> ap_const_lv12_36;
    static const sc_lv<9> ap_const_lv9_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<7> ap_const_lv7_40;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_D;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_F2_fu_212_p2();
    void thread_add_ln581_fu_224_p2();
    void thread_add_ln703_fu_518_p2();
    void thread_and_ln581_fu_310_p2();
    void thread_and_ln582_fu_295_p2();
    void thread_and_ln585_2_fu_327_p2();
    void thread_and_ln585_fu_315_p2();
    void thread_and_ln603_fu_344_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_arctan_V_address0();
    void thread_arctan_V_ce0();
    void thread_ashr_ln586_fu_281_p2();
    void thread_bitcast_ln696_fu_378_p1();
    void thread_exp_tmp_V_fu_162_p4();
    void thread_icmp_ln125_fu_426_p2();
    void thread_icmp_ln571_fu_206_p2();
    void thread_icmp_ln581_fu_218_p2();
    void thread_icmp_ln582_fu_244_p2();
    void thread_icmp_ln585_fu_267_p2();
    void thread_icmp_ln603_fu_272_p2();
    void thread_ireg_V_fu_146_p1();
    void thread_lhs_V_2_fu_498_p3();
    void thread_lhs_V_fu_474_p3();
    void thread_lshr_ln1333_fu_443_p2();
    void thread_man_V_3_fu_192_p2();
    void thread_man_V_4_fu_198_p3();
    void thread_mul_ln1193_fu_482_p0();
    void thread_mul_ln1193_fu_482_p1();
    void thread_mul_ln1193_fu_482_p2();
    void thread_mul_ln703_fu_506_p0();
    void thread_mul_ln703_fu_506_p1();
    void thread_mul_ln703_fu_506_p2();
    void thread_n_fu_432_p2();
    void thread_or_ln581_fu_333_p2();
    void thread_or_ln582_fu_300_p2();
    void thread_or_ln603_3_fu_363_p2();
    void thread_or_ln603_4_fu_369_p2();
    void thread_or_ln603_fu_350_p2();
    void thread_p_Result_32_fu_188_p1();
    void thread_p_Result_s_fu_154_p3();
    void thread_phi_V_fu_536_p3();
    void thread_ret_V_4_fu_512_p2();
    void thread_ret_V_5_fu_524_p2();
    void thread_ret_V_6_fu_530_p2();
    void thread_ret_V_fu_488_p2();
    void thread_select_ln588_fu_389_p3();
    void thread_select_ln603_4_fu_356_p3();
    void thread_select_ln603_5_fu_409_p3();
    void thread_select_ln603_6_fu_415_p3();
    void thread_select_ln603_fu_402_p3();
    void thread_sext_ln581_fu_264_p1();
    void thread_sh_amt_fu_236_p3();
    void thread_shl_ln604_fu_397_p2();
    void thread_sub_ln581_fu_230_p2();
    void thread_sub_ln703_fu_461_p2();
    void thread_tmp_10_fu_554_p4();
    void thread_tmp_11_fu_572_p4();
    void thread_tmp_12_fu_582_p4();
    void thread_tmp_29_fu_381_p3();
    void thread_tmp_30_fu_453_p3();
    void thread_tmp_fu_180_p3();
    void thread_tmp_s_fu_544_p4();
    void thread_trunc_ln556_fu_150_p1();
    void thread_trunc_ln565_fu_176_p1();
    void thread_trunc_ln581_fu_375_p1();
    void thread_trunc_ln583_fu_250_p1();
    void thread_trunc_ln586_fu_286_p1();
    void thread_xor_ln571_fu_290_p2();
    void thread_xor_ln581_fu_338_p2();
    void thread_xor_ln582_fu_304_p2();
    void thread_xor_ln585_fu_321_p2();
    void thread_z_i_V_fu_592_p3();
    void thread_z_r_V_fu_564_p3();
    void thread_zext_ln1118_fu_467_p1();
    void thread_zext_ln125_fu_422_p1();
    void thread_zext_ln126_1_fu_449_p1();
    void thread_zext_ln126_fu_438_p1();
    void thread_zext_ln461_fu_172_p1();
    void thread_zext_ln586_fu_277_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
