// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cordicSin_fix.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cordicSin_fix::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cordicSin_fix::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state1 = "1";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state2 = "10";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state3 = "100";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state4 = "1000";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state5 = "10000";
const sc_lv<6> cordicSin_fix::ap_ST_fsm_state6 = "100000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_1 = "1";
const sc_lv<32> cordicSin_fix::ap_const_lv32_2 = "10";
const sc_lv<32> cordicSin_fix::ap_const_lv32_3 = "11";
const sc_lv<32> cordicSin_fix::ap_const_lv32_4 = "100";
const sc_lv<1> cordicSin_fix::ap_const_lv1_0 = "0";
const sc_lv<32> cordicSin_fix::ap_const_lv32_5 = "101";
const sc_lv<8> cordicSin_fix::ap_const_lv8_0 = "00000000";
const sc_lv<8> cordicSin_fix::ap_const_lv8_26 = "100110";
const sc_lv<4> cordicSin_fix::ap_const_lv4_0 = "0000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_3F = "111111";
const sc_lv<32> cordicSin_fix::ap_const_lv32_34 = "110100";
const sc_lv<32> cordicSin_fix::ap_const_lv32_3E = "111110";
const sc_lv<1> cordicSin_fix::ap_const_lv1_1 = "1";
const sc_lv<54> cordicSin_fix::ap_const_lv54_0 = "000000000000000000000000000000000000000000000000000000";
const sc_lv<63> cordicSin_fix::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> cordicSin_fix::ap_const_lv12_433 = "10000110011";
const sc_lv<12> cordicSin_fix::ap_const_lv12_6 = "110";
const sc_lv<12> cordicSin_fix::ap_const_lv12_FFA = "111111111010";
const sc_lv<32> cordicSin_fix::ap_const_lv32_B = "1011";
const sc_lv<12> cordicSin_fix::ap_const_lv12_36 = "110110";
const sc_lv<9> cordicSin_fix::ap_const_lv9_0 = "000000000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_1F = "11111";
const sc_lv<8> cordicSin_fix::ap_const_lv8_FF = "11111111";
const sc_lv<4> cordicSin_fix::ap_const_lv4_A = "1010";
const sc_lv<4> cordicSin_fix::ap_const_lv4_1 = "1";
const sc_lv<7> cordicSin_fix::ap_const_lv7_40 = "1000000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_7 = "111";
const sc_lv<6> cordicSin_fix::ap_const_lv6_0 = "000000";
const sc_lv<32> cordicSin_fix::ap_const_lv32_6 = "110";
const sc_lv<32> cordicSin_fix::ap_const_lv32_D = "1101";
const bool cordicSin_fix::ap_const_boolean_1 = true;

cordicSin_fix::cordicSin_fix(sc_module_name name) : sc_module(name), mVcdFile(0) {
    arctan_V268_U = new cordicCos_fix_arckbM("arctan_V268_U");
    arctan_V268_U->clk(ap_clk);
    arctan_V268_U->reset(ap_rst);
    arctan_V268_U->address0(arctan_V268_address0);
    arctan_V268_U->ce0(arctan_V268_ce0);
    arctan_V268_U->q0(arctan_V268_q0);
    top_level_fpext_3lbW_U65 = new top_level_fpext_3lbW<1,2,32,64>("top_level_fpext_3lbW_U65");
    top_level_fpext_3lbW_U65->clk(ap_clk);
    top_level_fpext_3lbW_U65->reset(ap_rst);
    top_level_fpext_3lbW_U65->din0(x);
    top_level_fpext_3lbW_U65->ce(ap_var_for_const0);
    top_level_fpext_3lbW_U65->dout(grp_fu_142_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_F2_fu_212_p2);
    sensitive << ( zext_ln461_fu_172_p1 );

    SC_METHOD(thread_add_ln581_fu_224_p2);
    sensitive << ( F2_fu_212_p2 );

    SC_METHOD(thread_add_ln703_fu_518_p2);
    sensitive << ( p_Val2_18_reg_121 );
    sensitive << ( zext_ln100_1_fu_449_p1 );

    SC_METHOD(thread_and_ln581_fu_310_p2);
    sensitive << ( icmp_ln581_reg_617 );
    sensitive << ( xor_ln582_fu_304_p2 );

    SC_METHOD(thread_and_ln582_fu_295_p2);
    sensitive << ( icmp_ln582_reg_630 );
    sensitive << ( xor_ln571_fu_290_p2 );

    SC_METHOD(thread_and_ln585_1_fu_327_p2);
    sensitive << ( and_ln581_fu_310_p2 );
    sensitive << ( xor_ln585_fu_321_p2 );

    SC_METHOD(thread_and_ln585_fu_315_p2);
    sensitive << ( and_ln581_fu_310_p2 );
    sensitive << ( icmp_ln585_fu_267_p2 );

    SC_METHOD(thread_and_ln603_fu_344_p2);
    sensitive << ( icmp_ln603_fu_272_p2 );
    sensitive << ( xor_ln581_fu_338_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln99_fu_426_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln99_fu_426_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln99_fu_426_p2 );
    sensitive << ( z_i_old_V_reg_97 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_arctan_V268_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( zext_ln100_fu_438_p1 );

    SC_METHOD(thread_arctan_V268_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ashr_ln586_fu_281_p2);
    sensitive << ( man_V_2_reg_606 );
    sensitive << ( zext_ln586_fu_277_p1 );

    SC_METHOD(thread_bitcast_ln696_fu_378_p1);
    sensitive << ( x );

    SC_METHOD(thread_exp_tmp_V_fu_162_p4);
    sensitive << ( ireg_V_fu_146_p1 );

    SC_METHOD(thread_icmp_ln571_fu_206_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( trunc_ln556_fu_150_p1 );

    SC_METHOD(thread_icmp_ln581_fu_218_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( F2_fu_212_p2 );

    SC_METHOD(thread_icmp_ln582_fu_244_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( F2_fu_212_p2 );

    SC_METHOD(thread_icmp_ln585_fu_267_p2);
    sensitive << ( sh_amt_reg_623 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln603_fu_272_p2);
    sensitive << ( tmp_24_reg_642 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln99_fu_426_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ush_reg_131 );

    SC_METHOD(thread_ireg_V_fu_146_p1);
    sensitive << ( grp_fu_142_p1 );

    SC_METHOD(thread_lhs_V_1_fu_498_p3);
    sensitive << ( z_i_old_V_reg_97 );

    SC_METHOD(thread_lhs_V_fu_474_p3);
    sensitive << ( z_r_old_V_reg_109 );

    SC_METHOD(thread_lshr_ln1333_fu_443_p2);
    sensitive << ( zext_ln99_fu_422_p1 );

    SC_METHOD(thread_man_V_1_fu_192_p2);
    sensitive << ( p_Result_31_fu_188_p1 );

    SC_METHOD(thread_man_V_2_fu_198_p3);
    sensitive << ( p_Result_31_fu_188_p1 );
    sensitive << ( p_Result_s_fu_154_p3 );
    sensitive << ( man_V_1_fu_192_p2 );

    SC_METHOD(thread_mul_ln1192_fu_506_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln1118_fu_471_p1 );

    SC_METHOD(thread_mul_ln1192_fu_506_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( z_r_old_V_reg_109 );

    SC_METHOD(thread_mul_ln1192_fu_506_p2);
    sensitive << ( mul_ln1192_fu_506_p0 );
    sensitive << ( mul_ln1192_fu_506_p1 );

    SC_METHOD(thread_mul_ln1193_fu_482_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln1118_fu_471_p1 );

    SC_METHOD(thread_mul_ln1193_fu_482_p1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( z_i_old_V_reg_97 );

    SC_METHOD(thread_mul_ln1193_fu_482_p2);
    sensitive << ( mul_ln1193_fu_482_p0 );
    sensitive << ( mul_ln1193_fu_482_p1 );

    SC_METHOD(thread_n_fu_432_p2);
    sensitive << ( ush_reg_131 );

    SC_METHOD(thread_or_ln581_fu_333_p2);
    sensitive << ( icmp_ln581_reg_617 );
    sensitive << ( or_ln582_fu_300_p2 );

    SC_METHOD(thread_or_ln582_fu_300_p2);
    sensitive << ( icmp_ln571_reg_611 );
    sensitive << ( icmp_ln582_reg_630 );

    SC_METHOD(thread_or_ln603_1_fu_363_p2);
    sensitive << ( and_ln585_fu_315_p2 );
    sensitive << ( and_ln582_fu_295_p2 );

    SC_METHOD(thread_or_ln603_2_fu_369_p2);
    sensitive << ( or_ln603_fu_350_p2 );
    sensitive << ( or_ln603_1_fu_363_p2 );

    SC_METHOD(thread_or_ln603_fu_350_p2);
    sensitive << ( and_ln603_fu_344_p2 );
    sensitive << ( and_ln585_1_fu_327_p2 );

    SC_METHOD(thread_p_Result_31_fu_188_p1);
    sensitive << ( tmp_fu_180_p3 );

    SC_METHOD(thread_p_Result_s_fu_154_p3);
    sensitive << ( ireg_V_fu_146_p1 );

    SC_METHOD(thread_phi_V_fu_536_p3);
    sensitive << ( tmp_26_fu_453_p3 );
    sensitive << ( add_ln703_fu_518_p2 );
    sensitive << ( sub_ln703_fu_461_p2 );

    SC_METHOD(thread_ret_V_1_fu_512_p2);
    sensitive << ( mul_ln1192_fu_506_p2 );
    sensitive << ( lhs_V_1_fu_498_p3 );

    SC_METHOD(thread_ret_V_2_fu_524_p2);
    sensitive << ( lhs_V_fu_474_p3 );
    sensitive << ( mul_ln1193_fu_482_p2 );

    SC_METHOD(thread_ret_V_3_fu_530_p2);
    sensitive << ( mul_ln1192_fu_506_p2 );
    sensitive << ( lhs_V_1_fu_498_p3 );

    SC_METHOD(thread_ret_V_fu_488_p2);
    sensitive << ( lhs_V_fu_474_p3 );
    sensitive << ( mul_ln1193_fu_482_p2 );

    SC_METHOD(thread_select_ln588_fu_389_p3);
    sensitive << ( tmp_25_fu_381_p3 );

    SC_METHOD(thread_select_ln603_1_fu_356_p3);
    sensitive << ( trunc_ln583_reg_636 );
    sensitive << ( and_ln585_fu_315_p2 );
    sensitive << ( trunc_ln586_fu_286_p1 );

    SC_METHOD(thread_select_ln603_2_fu_409_p3);
    sensitive << ( or_ln603_reg_652 );
    sensitive << ( select_ln603_1_reg_657 );
    sensitive << ( select_ln603_fu_402_p3 );

    SC_METHOD(thread_select_ln603_3_fu_415_p3);
    sensitive << ( or_ln603_2_reg_662 );
    sensitive << ( select_ln603_2_fu_409_p3 );

    SC_METHOD(thread_select_ln603_fu_402_p3);
    sensitive << ( and_ln603_reg_647 );
    sensitive << ( shl_ln604_fu_397_p2 );
    sensitive << ( select_ln588_fu_389_p3 );

    SC_METHOD(thread_sext_ln581_fu_264_p1);
    sensitive << ( sh_amt_reg_623 );

    SC_METHOD(thread_sh_amt_fu_236_p3);
    sensitive << ( icmp_ln581_fu_218_p2 );
    sensitive << ( add_ln581_fu_224_p2 );
    sensitive << ( sub_ln581_fu_230_p2 );

    SC_METHOD(thread_shl_ln604_fu_397_p2);
    sensitive << ( trunc_ln583_reg_636 );
    sensitive << ( trunc_ln581_fu_375_p1 );

    SC_METHOD(thread_sub_ln581_fu_230_p2);
    sensitive << ( F2_fu_212_p2 );

    SC_METHOD(thread_sub_ln703_fu_461_p2);
    sensitive << ( p_Val2_18_reg_121 );
    sensitive << ( zext_ln100_1_fu_449_p1 );

    SC_METHOD(thread_tmp_25_fu_381_p3);
    sensitive << ( bitcast_ln696_fu_378_p1 );

    SC_METHOD(thread_tmp_26_fu_453_p3);
    sensitive << ( p_Val2_18_reg_121 );

    SC_METHOD(thread_tmp_7_fu_554_p4);
    sensitive << ( ret_V_2_fu_524_p2 );

    SC_METHOD(thread_tmp_8_fu_572_p4);
    sensitive << ( ret_V_1_fu_512_p2 );

    SC_METHOD(thread_tmp_9_fu_582_p4);
    sensitive << ( ret_V_3_fu_530_p2 );

    SC_METHOD(thread_tmp_fu_180_p3);
    sensitive << ( trunc_ln565_fu_176_p1 );

    SC_METHOD(thread_tmp_s_fu_544_p4);
    sensitive << ( ret_V_fu_488_p2 );

    SC_METHOD(thread_trunc_ln556_fu_150_p1);
    sensitive << ( ireg_V_fu_146_p1 );

    SC_METHOD(thread_trunc_ln565_fu_176_p1);
    sensitive << ( ireg_V_fu_146_p1 );

    SC_METHOD(thread_trunc_ln581_fu_375_p1);
    sensitive << ( sh_amt_reg_623 );

    SC_METHOD(thread_trunc_ln583_fu_250_p1);
    sensitive << ( man_V_2_fu_198_p3 );

    SC_METHOD(thread_trunc_ln586_fu_286_p1);
    sensitive << ( ashr_ln586_fu_281_p2 );

    SC_METHOD(thread_xor_ln571_fu_290_p2);
    sensitive << ( icmp_ln571_reg_611 );

    SC_METHOD(thread_xor_ln581_fu_338_p2);
    sensitive << ( or_ln581_fu_333_p2 );

    SC_METHOD(thread_xor_ln582_fu_304_p2);
    sensitive << ( or_ln582_fu_300_p2 );

    SC_METHOD(thread_xor_ln585_fu_321_p2);
    sensitive << ( icmp_ln585_fu_267_p2 );

    SC_METHOD(thread_z_i_V_fu_592_p3);
    sensitive << ( tmp_26_fu_453_p3 );
    sensitive << ( tmp_9_fu_582_p4 );
    sensitive << ( tmp_8_fu_572_p4 );

    SC_METHOD(thread_z_r_V_fu_564_p3);
    sensitive << ( tmp_26_fu_453_p3 );
    sensitive << ( tmp_7_fu_554_p4 );
    sensitive << ( tmp_s_fu_544_p4 );

    SC_METHOD(thread_zext_ln100_1_fu_449_p1);
    sensitive << ( arctan_V268_q0 );

    SC_METHOD(thread_zext_ln100_fu_438_p1);
    sensitive << ( ush_reg_131 );

    SC_METHOD(thread_zext_ln1118_fu_471_p1);
    sensitive << ( lshr_ln1333_reg_685 );

    SC_METHOD(thread_zext_ln461_fu_172_p1);
    sensitive << ( exp_tmp_V_fu_162_p4 );

    SC_METHOD(thread_zext_ln586_fu_277_p1);
    sensitive << ( sext_ln581_fu_264_p1 );

    SC_METHOD(thread_zext_ln99_fu_422_p1);
    sensitive << ( ush_reg_131 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln99_fu_426_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000001";
    ap_return_preg = "00000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cordicSin_fix_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x, "(port)x");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, arctan_V268_address0, "arctan_V268_address0");
    sc_trace(mVcdFile, arctan_V268_ce0, "arctan_V268_ce0");
    sc_trace(mVcdFile, arctan_V268_q0, "arctan_V268_q0");
    sc_trace(mVcdFile, man_V_2_fu_198_p3, "man_V_2_fu_198_p3");
    sc_trace(mVcdFile, man_V_2_reg_606, "man_V_2_reg_606");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln571_fu_206_p2, "icmp_ln571_fu_206_p2");
    sc_trace(mVcdFile, icmp_ln571_reg_611, "icmp_ln571_reg_611");
    sc_trace(mVcdFile, icmp_ln581_fu_218_p2, "icmp_ln581_fu_218_p2");
    sc_trace(mVcdFile, icmp_ln581_reg_617, "icmp_ln581_reg_617");
    sc_trace(mVcdFile, sh_amt_fu_236_p3, "sh_amt_fu_236_p3");
    sc_trace(mVcdFile, sh_amt_reg_623, "sh_amt_reg_623");
    sc_trace(mVcdFile, icmp_ln582_fu_244_p2, "icmp_ln582_fu_244_p2");
    sc_trace(mVcdFile, icmp_ln582_reg_630, "icmp_ln582_reg_630");
    sc_trace(mVcdFile, trunc_ln583_fu_250_p1, "trunc_ln583_fu_250_p1");
    sc_trace(mVcdFile, trunc_ln583_reg_636, "trunc_ln583_reg_636");
    sc_trace(mVcdFile, tmp_24_reg_642, "tmp_24_reg_642");
    sc_trace(mVcdFile, and_ln603_fu_344_p2, "and_ln603_fu_344_p2");
    sc_trace(mVcdFile, and_ln603_reg_647, "and_ln603_reg_647");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, or_ln603_fu_350_p2, "or_ln603_fu_350_p2");
    sc_trace(mVcdFile, or_ln603_reg_652, "or_ln603_reg_652");
    sc_trace(mVcdFile, select_ln603_1_fu_356_p3, "select_ln603_1_fu_356_p3");
    sc_trace(mVcdFile, select_ln603_1_reg_657, "select_ln603_1_reg_657");
    sc_trace(mVcdFile, or_ln603_2_fu_369_p2, "or_ln603_2_fu_369_p2");
    sc_trace(mVcdFile, or_ln603_2_reg_662, "or_ln603_2_reg_662");
    sc_trace(mVcdFile, select_ln603_3_fu_415_p3, "select_ln603_3_fu_415_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, n_fu_432_p2, "n_fu_432_p2");
    sc_trace(mVcdFile, n_reg_675, "n_reg_675");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln99_fu_426_p2, "icmp_ln99_fu_426_p2");
    sc_trace(mVcdFile, lshr_ln1333_fu_443_p2, "lshr_ln1333_fu_443_p2");
    sc_trace(mVcdFile, lshr_ln1333_reg_685, "lshr_ln1333_reg_685");
    sc_trace(mVcdFile, phi_V_fu_536_p3, "phi_V_fu_536_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, z_r_V_fu_564_p3, "z_r_V_fu_564_p3");
    sc_trace(mVcdFile, z_i_V_fu_592_p3, "z_i_V_fu_592_p3");
    sc_trace(mVcdFile, z_i_old_V_reg_97, "z_i_old_V_reg_97");
    sc_trace(mVcdFile, z_r_old_V_reg_109, "z_r_old_V_reg_109");
    sc_trace(mVcdFile, p_Val2_18_reg_121, "p_Val2_18_reg_121");
    sc_trace(mVcdFile, ush_reg_131, "ush_reg_131");
    sc_trace(mVcdFile, zext_ln100_fu_438_p1, "zext_ln100_fu_438_p1");
    sc_trace(mVcdFile, grp_fu_142_p1, "grp_fu_142_p1");
    sc_trace(mVcdFile, ireg_V_fu_146_p1, "ireg_V_fu_146_p1");
    sc_trace(mVcdFile, exp_tmp_V_fu_162_p4, "exp_tmp_V_fu_162_p4");
    sc_trace(mVcdFile, trunc_ln565_fu_176_p1, "trunc_ln565_fu_176_p1");
    sc_trace(mVcdFile, tmp_fu_180_p3, "tmp_fu_180_p3");
    sc_trace(mVcdFile, p_Result_31_fu_188_p1, "p_Result_31_fu_188_p1");
    sc_trace(mVcdFile, p_Result_s_fu_154_p3, "p_Result_s_fu_154_p3");
    sc_trace(mVcdFile, man_V_1_fu_192_p2, "man_V_1_fu_192_p2");
    sc_trace(mVcdFile, trunc_ln556_fu_150_p1, "trunc_ln556_fu_150_p1");
    sc_trace(mVcdFile, zext_ln461_fu_172_p1, "zext_ln461_fu_172_p1");
    sc_trace(mVcdFile, F2_fu_212_p2, "F2_fu_212_p2");
    sc_trace(mVcdFile, add_ln581_fu_224_p2, "add_ln581_fu_224_p2");
    sc_trace(mVcdFile, sub_ln581_fu_230_p2, "sub_ln581_fu_230_p2");
    sc_trace(mVcdFile, sext_ln581_fu_264_p1, "sext_ln581_fu_264_p1");
    sc_trace(mVcdFile, zext_ln586_fu_277_p1, "zext_ln586_fu_277_p1");
    sc_trace(mVcdFile, ashr_ln586_fu_281_p2, "ashr_ln586_fu_281_p2");
    sc_trace(mVcdFile, xor_ln571_fu_290_p2, "xor_ln571_fu_290_p2");
    sc_trace(mVcdFile, or_ln582_fu_300_p2, "or_ln582_fu_300_p2");
    sc_trace(mVcdFile, xor_ln582_fu_304_p2, "xor_ln582_fu_304_p2");
    sc_trace(mVcdFile, and_ln581_fu_310_p2, "and_ln581_fu_310_p2");
    sc_trace(mVcdFile, icmp_ln585_fu_267_p2, "icmp_ln585_fu_267_p2");
    sc_trace(mVcdFile, xor_ln585_fu_321_p2, "xor_ln585_fu_321_p2");
    sc_trace(mVcdFile, or_ln581_fu_333_p2, "or_ln581_fu_333_p2");
    sc_trace(mVcdFile, icmp_ln603_fu_272_p2, "icmp_ln603_fu_272_p2");
    sc_trace(mVcdFile, xor_ln581_fu_338_p2, "xor_ln581_fu_338_p2");
    sc_trace(mVcdFile, and_ln585_1_fu_327_p2, "and_ln585_1_fu_327_p2");
    sc_trace(mVcdFile, and_ln585_fu_315_p2, "and_ln585_fu_315_p2");
    sc_trace(mVcdFile, trunc_ln586_fu_286_p1, "trunc_ln586_fu_286_p1");
    sc_trace(mVcdFile, and_ln582_fu_295_p2, "and_ln582_fu_295_p2");
    sc_trace(mVcdFile, or_ln603_1_fu_363_p2, "or_ln603_1_fu_363_p2");
    sc_trace(mVcdFile, bitcast_ln696_fu_378_p1, "bitcast_ln696_fu_378_p1");
    sc_trace(mVcdFile, tmp_25_fu_381_p3, "tmp_25_fu_381_p3");
    sc_trace(mVcdFile, trunc_ln581_fu_375_p1, "trunc_ln581_fu_375_p1");
    sc_trace(mVcdFile, shl_ln604_fu_397_p2, "shl_ln604_fu_397_p2");
    sc_trace(mVcdFile, select_ln588_fu_389_p3, "select_ln588_fu_389_p3");
    sc_trace(mVcdFile, select_ln603_fu_402_p3, "select_ln603_fu_402_p3");
    sc_trace(mVcdFile, select_ln603_2_fu_409_p3, "select_ln603_2_fu_409_p3");
    sc_trace(mVcdFile, zext_ln99_fu_422_p1, "zext_ln99_fu_422_p1");
    sc_trace(mVcdFile, zext_ln100_1_fu_449_p1, "zext_ln100_1_fu_449_p1");
    sc_trace(mVcdFile, mul_ln1193_fu_482_p0, "mul_ln1193_fu_482_p0");
    sc_trace(mVcdFile, zext_ln1118_fu_471_p1, "zext_ln1118_fu_471_p1");
    sc_trace(mVcdFile, mul_ln1193_fu_482_p1, "mul_ln1193_fu_482_p1");
    sc_trace(mVcdFile, lhs_V_fu_474_p3, "lhs_V_fu_474_p3");
    sc_trace(mVcdFile, mul_ln1193_fu_482_p2, "mul_ln1193_fu_482_p2");
    sc_trace(mVcdFile, mul_ln1192_fu_506_p0, "mul_ln1192_fu_506_p0");
    sc_trace(mVcdFile, mul_ln1192_fu_506_p1, "mul_ln1192_fu_506_p1");
    sc_trace(mVcdFile, mul_ln1192_fu_506_p2, "mul_ln1192_fu_506_p2");
    sc_trace(mVcdFile, lhs_V_1_fu_498_p3, "lhs_V_1_fu_498_p3");
    sc_trace(mVcdFile, tmp_26_fu_453_p3, "tmp_26_fu_453_p3");
    sc_trace(mVcdFile, add_ln703_fu_518_p2, "add_ln703_fu_518_p2");
    sc_trace(mVcdFile, sub_ln703_fu_461_p2, "sub_ln703_fu_461_p2");
    sc_trace(mVcdFile, ret_V_fu_488_p2, "ret_V_fu_488_p2");
    sc_trace(mVcdFile, ret_V_2_fu_524_p2, "ret_V_2_fu_524_p2");
    sc_trace(mVcdFile, tmp_7_fu_554_p4, "tmp_7_fu_554_p4");
    sc_trace(mVcdFile, tmp_s_fu_544_p4, "tmp_s_fu_544_p4");
    sc_trace(mVcdFile, ret_V_1_fu_512_p2, "ret_V_1_fu_512_p2");
    sc_trace(mVcdFile, ret_V_3_fu_530_p2, "ret_V_3_fu_530_p2");
    sc_trace(mVcdFile, tmp_9_fu_582_p4, "tmp_9_fu_582_p4");
    sc_trace(mVcdFile, tmp_8_fu_572_p4, "tmp_8_fu_572_p4");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

cordicSin_fix::~cordicSin_fix() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete arctan_V268_U;
    delete top_level_fpext_3lbW_U65;
}

void cordicSin_fix::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void cordicSin_fix::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
             esl_seteq<1,1,1>(icmp_ln99_fu_426_p2.read(), ap_const_lv1_1))) {
            ap_return_preg = z_i_old_V_reg_97.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_Val2_18_reg_121 = select_ln603_3_fu_415_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        p_Val2_18_reg_121 = phi_V_fu_536_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        ush_reg_131 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ush_reg_131 = n_reg_675.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        z_i_old_V_reg_97 = ap_const_lv8_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        z_i_old_V_reg_97 = z_i_V_fu_592_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        z_r_old_V_reg_109 = ap_const_lv8_26;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        z_r_old_V_reg_109 = z_r_V_fu_564_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        and_ln603_reg_647 = and_ln603_fu_344_p2.read();
        or_ln603_2_reg_662 = or_ln603_2_fu_369_p2.read();
        or_ln603_reg_652 = or_ln603_fu_350_p2.read();
        select_ln603_1_reg_657 = select_ln603_1_fu_356_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        icmp_ln571_reg_611 = icmp_ln571_fu_206_p2.read();
        icmp_ln581_reg_617 = icmp_ln581_fu_218_p2.read();
        icmp_ln582_reg_630 = icmp_ln582_fu_244_p2.read();
        man_V_2_reg_606 = man_V_2_fu_198_p3.read();
        sh_amt_reg_623 = sh_amt_fu_236_p3.read();
        tmp_24_reg_642 = sh_amt_fu_236_p3.read().range(11, 3);
        trunc_ln583_reg_636 = trunc_ln583_fu_250_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln99_fu_426_p2.read(), ap_const_lv1_0))) {
        lshr_ln1333_reg_685 = lshr_ln1333_fu_443_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        n_reg_675 = n_fu_432_p2.read();
    }
}

void cordicSin_fix::thread_F2_fu_212_p2() {
    F2_fu_212_p2 = (!ap_const_lv12_433.is_01() || !zext_ln461_fu_172_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_433) - sc_biguint<12>(zext_ln461_fu_172_p1.read()));
}

void cordicSin_fix::thread_add_ln581_fu_224_p2() {
    add_ln581_fu_224_p2 = (!ap_const_lv12_FFA.is_01() || !F2_fu_212_p2.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FFA) + sc_biguint<12>(F2_fu_212_p2.read()));
}

void cordicSin_fix::thread_add_ln703_fu_518_p2() {
    add_ln703_fu_518_p2 = (!p_Val2_18_reg_121.read().is_01() || !zext_ln100_1_fu_449_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_18_reg_121.read()) + sc_biguint<8>(zext_ln100_1_fu_449_p1.read()));
}

void cordicSin_fix::thread_and_ln581_fu_310_p2() {
    and_ln581_fu_310_p2 = (icmp_ln581_reg_617.read() & xor_ln582_fu_304_p2.read());
}

void cordicSin_fix::thread_and_ln582_fu_295_p2() {
    and_ln582_fu_295_p2 = (icmp_ln582_reg_630.read() & xor_ln571_fu_290_p2.read());
}

void cordicSin_fix::thread_and_ln585_1_fu_327_p2() {
    and_ln585_1_fu_327_p2 = (and_ln581_fu_310_p2.read() & xor_ln585_fu_321_p2.read());
}

void cordicSin_fix::thread_and_ln585_fu_315_p2() {
    and_ln585_fu_315_p2 = (and_ln581_fu_310_p2.read() & icmp_ln585_fu_267_p2.read());
}

void cordicSin_fix::thread_and_ln603_fu_344_p2() {
    and_ln603_fu_344_p2 = (icmp_ln603_fu_272_p2.read() & xor_ln581_fu_338_p2.read());
}

void cordicSin_fix::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cordicSin_fix::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cordicSin_fix::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cordicSin_fix::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void cordicSin_fix::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void cordicSin_fix::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void cordicSin_fix::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(icmp_ln99_fu_426_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cordicSin_fix::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cordicSin_fix::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln99_fu_426_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cordicSin_fix::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln99_fu_426_p2.read(), ap_const_lv1_1))) {
        ap_return = z_i_old_V_reg_97.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void cordicSin_fix::thread_arctan_V268_address0() {
    arctan_V268_address0 =  (sc_lv<6>) (zext_ln100_fu_438_p1.read());
}

void cordicSin_fix::thread_arctan_V268_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        arctan_V268_ce0 = ap_const_logic_1;
    } else {
        arctan_V268_ce0 = ap_const_logic_0;
    }
}

void cordicSin_fix::thread_ashr_ln586_fu_281_p2() {
    ashr_ln586_fu_281_p2 = (!man_V_2_reg_606.read().is_01() || !zext_ln586_fu_277_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(man_V_2_reg_606.read()) >> (unsigned short)zext_ln586_fu_277_p1.read().to_uint();
}

void cordicSin_fix::thread_bitcast_ln696_fu_378_p1() {
    bitcast_ln696_fu_378_p1 = x.read();
}

void cordicSin_fix::thread_exp_tmp_V_fu_162_p4() {
    exp_tmp_V_fu_162_p4 = ireg_V_fu_146_p1.read().range(62, 52);
}

void cordicSin_fix::thread_icmp_ln571_fu_206_p2() {
    icmp_ln571_fu_206_p2 = (!trunc_ln556_fu_150_p1.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln556_fu_150_p1.read() == ap_const_lv63_0);
}

void cordicSin_fix::thread_icmp_ln581_fu_218_p2() {
    icmp_ln581_fu_218_p2 = (!F2_fu_212_p2.read().is_01() || !ap_const_lv12_6.is_01())? sc_lv<1>(): (sc_bigint<12>(F2_fu_212_p2.read()) > sc_bigint<12>(ap_const_lv12_6));
}

void cordicSin_fix::thread_icmp_ln582_fu_244_p2() {
    icmp_ln582_fu_244_p2 = (!F2_fu_212_p2.read().is_01() || !ap_const_lv12_6.is_01())? sc_lv<1>(): sc_lv<1>(F2_fu_212_p2.read() == ap_const_lv12_6);
}

void cordicSin_fix::thread_icmp_ln585_fu_267_p2() {
    icmp_ln585_fu_267_p2 = (!sh_amt_reg_623.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_biguint<12>(sh_amt_reg_623.read()) < sc_biguint<12>(ap_const_lv12_36));
}

void cordicSin_fix::thread_icmp_ln603_fu_272_p2() {
    icmp_ln603_fu_272_p2 = (!tmp_24_reg_642.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_24_reg_642.read() == ap_const_lv9_0);
}

void cordicSin_fix::thread_icmp_ln99_fu_426_p2() {
    icmp_ln99_fu_426_p2 = (!ush_reg_131.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(ush_reg_131.read() == ap_const_lv4_A);
}

void cordicSin_fix::thread_ireg_V_fu_146_p1() {
    ireg_V_fu_146_p1 = grp_fu_142_p1.read();
}

void cordicSin_fix::thread_lhs_V_1_fu_498_p3() {
    lhs_V_1_fu_498_p3 = esl_concat<8,6>(z_i_old_V_reg_97.read(), ap_const_lv6_0);
}

void cordicSin_fix::thread_lhs_V_fu_474_p3() {
    lhs_V_fu_474_p3 = esl_concat<8,6>(z_r_old_V_reg_109.read(), ap_const_lv6_0);
}

void cordicSin_fix::thread_lshr_ln1333_fu_443_p2() {
    lshr_ln1333_fu_443_p2 = (!zext_ln99_fu_422_p1.read().is_01())? sc_lv<7>(): ap_const_lv7_40 >> (unsigned short)zext_ln99_fu_422_p1.read().to_uint();
}

void cordicSin_fix::thread_man_V_1_fu_192_p2() {
    man_V_1_fu_192_p2 = (!ap_const_lv54_0.is_01() || !p_Result_31_fu_188_p1.read().is_01())? sc_lv<54>(): (sc_biguint<54>(ap_const_lv54_0) - sc_biguint<54>(p_Result_31_fu_188_p1.read()));
}

void cordicSin_fix::thread_man_V_2_fu_198_p3() {
    man_V_2_fu_198_p3 = (!p_Result_s_fu_154_p3.read()[0].is_01())? sc_lv<54>(): ((p_Result_s_fu_154_p3.read()[0].to_bool())? man_V_1_fu_192_p2.read(): p_Result_31_fu_188_p1.read());
}

void cordicSin_fix::thread_mul_ln1192_fu_506_p0() {
    mul_ln1192_fu_506_p0 =  (sc_lv<7>) (zext_ln1118_fu_471_p1.read());
}

void cordicSin_fix::thread_mul_ln1192_fu_506_p1() {
    mul_ln1192_fu_506_p1 = z_r_old_V_reg_109.read();
}

void cordicSin_fix::thread_mul_ln1192_fu_506_p2() {
    mul_ln1192_fu_506_p2 = (!mul_ln1192_fu_506_p0.read().is_01() || !mul_ln1192_fu_506_p1.read().is_01())? sc_lv<14>(): sc_biguint<7>(mul_ln1192_fu_506_p0.read()) * sc_bigint<8>(mul_ln1192_fu_506_p1.read());
}

void cordicSin_fix::thread_mul_ln1193_fu_482_p0() {
    mul_ln1193_fu_482_p0 =  (sc_lv<7>) (zext_ln1118_fu_471_p1.read());
}

void cordicSin_fix::thread_mul_ln1193_fu_482_p1() {
    mul_ln1193_fu_482_p1 = z_i_old_V_reg_97.read();
}

void cordicSin_fix::thread_mul_ln1193_fu_482_p2() {
    mul_ln1193_fu_482_p2 = (!mul_ln1193_fu_482_p0.read().is_01() || !mul_ln1193_fu_482_p1.read().is_01())? sc_lv<14>(): sc_biguint<7>(mul_ln1193_fu_482_p0.read()) * sc_bigint<8>(mul_ln1193_fu_482_p1.read());
}

void cordicSin_fix::thread_n_fu_432_p2() {
    n_fu_432_p2 = (!ush_reg_131.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(ush_reg_131.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void cordicSin_fix::thread_or_ln581_fu_333_p2() {
    or_ln581_fu_333_p2 = (or_ln582_fu_300_p2.read() | icmp_ln581_reg_617.read());
}

void cordicSin_fix::thread_or_ln582_fu_300_p2() {
    or_ln582_fu_300_p2 = (icmp_ln571_reg_611.read() | icmp_ln582_reg_630.read());
}

void cordicSin_fix::thread_or_ln603_1_fu_363_p2() {
    or_ln603_1_fu_363_p2 = (and_ln585_fu_315_p2.read() | and_ln582_fu_295_p2.read());
}

void cordicSin_fix::thread_or_ln603_2_fu_369_p2() {
    or_ln603_2_fu_369_p2 = (or_ln603_fu_350_p2.read() | or_ln603_1_fu_363_p2.read());
}

void cordicSin_fix::thread_or_ln603_fu_350_p2() {
    or_ln603_fu_350_p2 = (and_ln603_fu_344_p2.read() | and_ln585_1_fu_327_p2.read());
}

void cordicSin_fix::thread_p_Result_31_fu_188_p1() {
    p_Result_31_fu_188_p1 = esl_zext<54,53>(tmp_fu_180_p3.read());
}

void cordicSin_fix::thread_p_Result_s_fu_154_p3() {
    p_Result_s_fu_154_p3 = ireg_V_fu_146_p1.read().range(63, 63);
}

void cordicSin_fix::thread_phi_V_fu_536_p3() {
    phi_V_fu_536_p3 = (!tmp_26_fu_453_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_26_fu_453_p3.read()[0].to_bool())? add_ln703_fu_518_p2.read(): sub_ln703_fu_461_p2.read());
}

void cordicSin_fix::thread_ret_V_1_fu_512_p2() {
    ret_V_1_fu_512_p2 = (!mul_ln1192_fu_506_p2.read().is_01() || !lhs_V_1_fu_498_p3.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln1192_fu_506_p2.read()) + sc_biguint<14>(lhs_V_1_fu_498_p3.read()));
}

void cordicSin_fix::thread_ret_V_2_fu_524_p2() {
    ret_V_2_fu_524_p2 = (!lhs_V_fu_474_p3.read().is_01() || !mul_ln1193_fu_482_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(lhs_V_fu_474_p3.read()) + sc_biguint<14>(mul_ln1193_fu_482_p2.read()));
}

void cordicSin_fix::thread_ret_V_3_fu_530_p2() {
    ret_V_3_fu_530_p2 = (!lhs_V_1_fu_498_p3.read().is_01() || !mul_ln1192_fu_506_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(lhs_V_1_fu_498_p3.read()) - sc_biguint<14>(mul_ln1192_fu_506_p2.read()));
}

void cordicSin_fix::thread_ret_V_fu_488_p2() {
    ret_V_fu_488_p2 = (!lhs_V_fu_474_p3.read().is_01() || !mul_ln1193_fu_482_p2.read().is_01())? sc_lv<14>(): (sc_biguint<14>(lhs_V_fu_474_p3.read()) - sc_biguint<14>(mul_ln1193_fu_482_p2.read()));
}

void cordicSin_fix::thread_select_ln588_fu_389_p3() {
    select_ln588_fu_389_p3 = (!tmp_25_fu_381_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_25_fu_381_p3.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void cordicSin_fix::thread_select_ln603_1_fu_356_p3() {
    select_ln603_1_fu_356_p3 = (!and_ln585_fu_315_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln585_fu_315_p2.read()[0].to_bool())? trunc_ln586_fu_286_p1.read(): trunc_ln583_reg_636.read());
}

void cordicSin_fix::thread_select_ln603_2_fu_409_p3() {
    select_ln603_2_fu_409_p3 = (!or_ln603_reg_652.read()[0].is_01())? sc_lv<8>(): ((or_ln603_reg_652.read()[0].to_bool())? select_ln603_fu_402_p3.read(): select_ln603_1_reg_657.read());
}

void cordicSin_fix::thread_select_ln603_3_fu_415_p3() {
    select_ln603_3_fu_415_p3 = (!or_ln603_2_reg_662.read()[0].is_01())? sc_lv<8>(): ((or_ln603_2_reg_662.read()[0].to_bool())? select_ln603_2_fu_409_p3.read(): ap_const_lv8_0);
}

void cordicSin_fix::thread_select_ln603_fu_402_p3() {
    select_ln603_fu_402_p3 = (!and_ln603_reg_647.read()[0].is_01())? sc_lv<8>(): ((and_ln603_reg_647.read()[0].to_bool())? shl_ln604_fu_397_p2.read(): select_ln588_fu_389_p3.read());
}

void cordicSin_fix::thread_sext_ln581_fu_264_p1() {
    sext_ln581_fu_264_p1 = esl_sext<32,12>(sh_amt_reg_623.read());
}

void cordicSin_fix::thread_sh_amt_fu_236_p3() {
    sh_amt_fu_236_p3 = (!icmp_ln581_fu_218_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln581_fu_218_p2.read()[0].to_bool())? add_ln581_fu_224_p2.read(): sub_ln581_fu_230_p2.read());
}

void cordicSin_fix::thread_shl_ln604_fu_397_p2() {
    shl_ln604_fu_397_p2 = (!trunc_ln581_fu_375_p1.read().is_01())? sc_lv<8>(): trunc_ln583_reg_636.read() << (unsigned short)trunc_ln581_fu_375_p1.read().to_uint();
}

void cordicSin_fix::thread_sub_ln581_fu_230_p2() {
    sub_ln581_fu_230_p2 = (!ap_const_lv12_6.is_01() || !F2_fu_212_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_6) - sc_biguint<12>(F2_fu_212_p2.read()));
}

void cordicSin_fix::thread_sub_ln703_fu_461_p2() {
    sub_ln703_fu_461_p2 = (!p_Val2_18_reg_121.read().is_01() || !zext_ln100_1_fu_449_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_18_reg_121.read()) - sc_biguint<8>(zext_ln100_1_fu_449_p1.read()));
}

void cordicSin_fix::thread_tmp_25_fu_381_p3() {
    tmp_25_fu_381_p3 = bitcast_ln696_fu_378_p1.read().range(31, 31);
}

void cordicSin_fix::thread_tmp_26_fu_453_p3() {
    tmp_26_fu_453_p3 = p_Val2_18_reg_121.read().range(7, 7);
}

void cordicSin_fix::thread_tmp_7_fu_554_p4() {
    tmp_7_fu_554_p4 = ret_V_2_fu_524_p2.read().range(13, 6);
}

void cordicSin_fix::thread_tmp_8_fu_572_p4() {
    tmp_8_fu_572_p4 = ret_V_1_fu_512_p2.read().range(13, 6);
}

void cordicSin_fix::thread_tmp_9_fu_582_p4() {
    tmp_9_fu_582_p4 = ret_V_3_fu_530_p2.read().range(13, 6);
}

void cordicSin_fix::thread_tmp_fu_180_p3() {
    tmp_fu_180_p3 = esl_concat<1,52>(ap_const_lv1_1, trunc_ln565_fu_176_p1.read());
}

void cordicSin_fix::thread_tmp_s_fu_544_p4() {
    tmp_s_fu_544_p4 = ret_V_fu_488_p2.read().range(13, 6);
}

void cordicSin_fix::thread_trunc_ln556_fu_150_p1() {
    trunc_ln556_fu_150_p1 = ireg_V_fu_146_p1.read().range(63-1, 0);
}

void cordicSin_fix::thread_trunc_ln565_fu_176_p1() {
    trunc_ln565_fu_176_p1 = ireg_V_fu_146_p1.read().range(52-1, 0);
}

void cordicSin_fix::thread_trunc_ln581_fu_375_p1() {
    trunc_ln581_fu_375_p1 = sh_amt_reg_623.read().range(8-1, 0);
}

void cordicSin_fix::thread_trunc_ln583_fu_250_p1() {
    trunc_ln583_fu_250_p1 = man_V_2_fu_198_p3.read().range(8-1, 0);
}

void cordicSin_fix::thread_trunc_ln586_fu_286_p1() {
    trunc_ln586_fu_286_p1 = ashr_ln586_fu_281_p2.read().range(8-1, 0);
}

void cordicSin_fix::thread_xor_ln571_fu_290_p2() {
    xor_ln571_fu_290_p2 = (icmp_ln571_reg_611.read() ^ ap_const_lv1_1);
}

void cordicSin_fix::thread_xor_ln581_fu_338_p2() {
    xor_ln581_fu_338_p2 = (or_ln581_fu_333_p2.read() ^ ap_const_lv1_1);
}

void cordicSin_fix::thread_xor_ln582_fu_304_p2() {
    xor_ln582_fu_304_p2 = (or_ln582_fu_300_p2.read() ^ ap_const_lv1_1);
}

void cordicSin_fix::thread_xor_ln585_fu_321_p2() {
    xor_ln585_fu_321_p2 = (icmp_ln585_fu_267_p2.read() ^ ap_const_lv1_1);
}

void cordicSin_fix::thread_z_i_V_fu_592_p3() {
    z_i_V_fu_592_p3 = (!tmp_26_fu_453_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_26_fu_453_p3.read()[0].to_bool())? tmp_9_fu_582_p4.read(): tmp_8_fu_572_p4.read());
}

void cordicSin_fix::thread_z_r_V_fu_564_p3() {
    z_r_V_fu_564_p3 = (!tmp_26_fu_453_p3.read()[0].is_01())? sc_lv<8>(): ((tmp_26_fu_453_p3.read()[0].to_bool())? tmp_7_fu_554_p4.read(): tmp_s_fu_544_p4.read());
}

void cordicSin_fix::thread_zext_ln100_1_fu_449_p1() {
    zext_ln100_1_fu_449_p1 = esl_zext<8,6>(arctan_V268_q0.read());
}

void cordicSin_fix::thread_zext_ln100_fu_438_p1() {
    zext_ln100_fu_438_p1 = esl_zext<64,4>(ush_reg_131.read());
}

void cordicSin_fix::thread_zext_ln1118_fu_471_p1() {
    zext_ln1118_fu_471_p1 = esl_zext<14,7>(lshr_ln1333_reg_685.read());
}

void cordicSin_fix::thread_zext_ln461_fu_172_p1() {
    zext_ln461_fu_172_p1 = esl_zext<12,11>(exp_tmp_V_fu_162_p4.read());
}

void cordicSin_fix::thread_zext_ln586_fu_277_p1() {
    zext_ln586_fu_277_p1 = esl_zext<54,32>(sext_ln581_fu_264_p1.read());
}

void cordicSin_fix::thread_zext_ln99_fu_422_p1() {
    zext_ln99_fu_422_p1 = esl_zext<7,4>(ush_reg_131.read());
}

void cordicSin_fix::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln99_fu_426_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}

}

