// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "top_level.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic top_level::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic top_level::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> top_level::ap_ST_fsm_state1 = "1";
const sc_lv<4> top_level::ap_ST_fsm_state2 = "10";
const sc_lv<4> top_level::ap_ST_fsm_state3 = "100";
const sc_lv<4> top_level::ap_ST_fsm_state4 = "1000";
const sc_lv<32> top_level::ap_const_lv32_1 = "1";
const sc_lv<32> top_level::ap_const_lv32_2 = "10";
const bool top_level::ap_const_boolean_0 = false;
const sc_lv<32> top_level::ap_const_lv32_3 = "11";
const bool top_level::ap_const_boolean_1 = true;

top_level::top_level(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_method1_fu_54 = new method1("grp_method1_fu_54");
    grp_method1_fu_54->ap_clk(ap_clk);
    grp_method1_fu_54->ap_rst(ap_rst_n_inv);
    grp_method1_fu_54->inputStream_TDATA(inputStream_TDATA_int);
    grp_method1_fu_54->inputStream_TKEEP(inputStream_TKEEP_int);
    grp_method1_fu_54->inputStream_TSTRB(inputStream_TSTRB_int);
    grp_method1_fu_54->inputStream_TUSER(inputStream_TUSER_int);
    grp_method1_fu_54->inputStream_TLAST(inputStream_TLAST_int);
    grp_method1_fu_54->inputStream_TID(inputStream_TID_int);
    grp_method1_fu_54->inputStream_TDEST(inputStream_TDEST_int);
    grp_method1_fu_54->outputStream_TDATA(grp_method1_fu_54_outputStream_TDATA);
    grp_method1_fu_54->outputStream_TKEEP(grp_method1_fu_54_outputStream_TKEEP);
    grp_method1_fu_54->outputStream_TSTRB(grp_method1_fu_54_outputStream_TSTRB);
    grp_method1_fu_54->outputStream_TUSER(grp_method1_fu_54_outputStream_TUSER);
    grp_method1_fu_54->outputStream_TLAST(grp_method1_fu_54_outputStream_TLAST);
    grp_method1_fu_54->outputStream_TID(grp_method1_fu_54_outputStream_TID);
    grp_method1_fu_54->outputStream_TDEST(grp_method1_fu_54_outputStream_TDEST);
    grp_method1_fu_54->ap_start(grp_method1_fu_54_ap_start);
    grp_method1_fu_54->inputStream_TVALID(inputStream_TVALID_int);
    grp_method1_fu_54->inputStream_TREADY(grp_method1_fu_54_inputStream_TREADY);
    grp_method1_fu_54->outputStream_TVALID(grp_method1_fu_54_outputStream_TVALID);
    grp_method1_fu_54->outputStream_TREADY(grp_method1_fu_54_outputStream_TREADY);
    grp_method1_fu_54->ap_done(grp_method1_fu_54_ap_done);
    grp_method1_fu_54->ap_ready(grp_method1_fu_54_ap_ready);
    grp_method1_fu_54->ap_idle(grp_method1_fu_54_ap_idle);
    grp_method1_fu_54->ap_continue(grp_method1_fu_54_ap_continue);
    regslice_both_inputStream_V_data_V_U = new regslice_both<32>("regslice_both_inputStream_V_data_V_U");
    regslice_both_inputStream_V_data_V_U->ap_clk(ap_clk);
    regslice_both_inputStream_V_data_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_inputStream_V_data_V_U->data_in(inputStream_TDATA);
    regslice_both_inputStream_V_data_V_U->vld_in(inputStream_TVALID);
    regslice_both_inputStream_V_data_V_U->ack_in(regslice_both_inputStream_V_data_V_U_ack_in);
    regslice_both_inputStream_V_data_V_U->data_out(inputStream_TDATA_int);
    regslice_both_inputStream_V_data_V_U->vld_out(inputStream_TVALID_int);
    regslice_both_inputStream_V_data_V_U->ack_out(inputStream_TREADY_int);
    regslice_both_inputStream_V_data_V_U->apdone_blk(regslice_both_inputStream_V_data_V_U_apdone_blk);
    regslice_both_inputStream_V_keep_V_U = new regslice_both<4>("regslice_both_inputStream_V_keep_V_U");
    regslice_both_inputStream_V_keep_V_U->ap_clk(ap_clk);
    regslice_both_inputStream_V_keep_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_inputStream_V_keep_V_U->data_in(inputStream_TKEEP);
    regslice_both_inputStream_V_keep_V_U->vld_in(inputStream_TVALID);
    regslice_both_inputStream_V_keep_V_U->ack_in(regslice_both_inputStream_V_keep_V_U_ack_in);
    regslice_both_inputStream_V_keep_V_U->data_out(inputStream_TKEEP_int);
    regslice_both_inputStream_V_keep_V_U->vld_out(regslice_both_inputStream_V_keep_V_U_vld_out);
    regslice_both_inputStream_V_keep_V_U->ack_out(inputStream_TREADY_int);
    regslice_both_inputStream_V_keep_V_U->apdone_blk(regslice_both_inputStream_V_keep_V_U_apdone_blk);
    regslice_both_inputStream_V_strb_V_U = new regslice_both<4>("regslice_both_inputStream_V_strb_V_U");
    regslice_both_inputStream_V_strb_V_U->ap_clk(ap_clk);
    regslice_both_inputStream_V_strb_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_inputStream_V_strb_V_U->data_in(inputStream_TSTRB);
    regslice_both_inputStream_V_strb_V_U->vld_in(inputStream_TVALID);
    regslice_both_inputStream_V_strb_V_U->ack_in(regslice_both_inputStream_V_strb_V_U_ack_in);
    regslice_both_inputStream_V_strb_V_U->data_out(inputStream_TSTRB_int);
    regslice_both_inputStream_V_strb_V_U->vld_out(regslice_both_inputStream_V_strb_V_U_vld_out);
    regslice_both_inputStream_V_strb_V_U->ack_out(inputStream_TREADY_int);
    regslice_both_inputStream_V_strb_V_U->apdone_blk(regslice_both_inputStream_V_strb_V_U_apdone_blk);
    regslice_both_inputStream_V_user_V_U = new regslice_both<1>("regslice_both_inputStream_V_user_V_U");
    regslice_both_inputStream_V_user_V_U->ap_clk(ap_clk);
    regslice_both_inputStream_V_user_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_inputStream_V_user_V_U->data_in(inputStream_TUSER);
    regslice_both_inputStream_V_user_V_U->vld_in(inputStream_TVALID);
    regslice_both_inputStream_V_user_V_U->ack_in(regslice_both_inputStream_V_user_V_U_ack_in);
    regslice_both_inputStream_V_user_V_U->data_out(inputStream_TUSER_int);
    regslice_both_inputStream_V_user_V_U->vld_out(regslice_both_inputStream_V_user_V_U_vld_out);
    regslice_both_inputStream_V_user_V_U->ack_out(inputStream_TREADY_int);
    regslice_both_inputStream_V_user_V_U->apdone_blk(regslice_both_inputStream_V_user_V_U_apdone_blk);
    regslice_both_inputStream_V_last_V_U = new regslice_both<1>("regslice_both_inputStream_V_last_V_U");
    regslice_both_inputStream_V_last_V_U->ap_clk(ap_clk);
    regslice_both_inputStream_V_last_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_inputStream_V_last_V_U->data_in(inputStream_TLAST);
    regslice_both_inputStream_V_last_V_U->vld_in(inputStream_TVALID);
    regslice_both_inputStream_V_last_V_U->ack_in(regslice_both_inputStream_V_last_V_U_ack_in);
    regslice_both_inputStream_V_last_V_U->data_out(inputStream_TLAST_int);
    regslice_both_inputStream_V_last_V_U->vld_out(regslice_both_inputStream_V_last_V_U_vld_out);
    regslice_both_inputStream_V_last_V_U->ack_out(inputStream_TREADY_int);
    regslice_both_inputStream_V_last_V_U->apdone_blk(regslice_both_inputStream_V_last_V_U_apdone_blk);
    regslice_both_inputStream_V_id_V_U = new regslice_both<1>("regslice_both_inputStream_V_id_V_U");
    regslice_both_inputStream_V_id_V_U->ap_clk(ap_clk);
    regslice_both_inputStream_V_id_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_inputStream_V_id_V_U->data_in(inputStream_TID);
    regslice_both_inputStream_V_id_V_U->vld_in(inputStream_TVALID);
    regslice_both_inputStream_V_id_V_U->ack_in(regslice_both_inputStream_V_id_V_U_ack_in);
    regslice_both_inputStream_V_id_V_U->data_out(inputStream_TID_int);
    regslice_both_inputStream_V_id_V_U->vld_out(regslice_both_inputStream_V_id_V_U_vld_out);
    regslice_both_inputStream_V_id_V_U->ack_out(inputStream_TREADY_int);
    regslice_both_inputStream_V_id_V_U->apdone_blk(regslice_both_inputStream_V_id_V_U_apdone_blk);
    regslice_both_inputStream_V_dest_V_U = new regslice_both<1>("regslice_both_inputStream_V_dest_V_U");
    regslice_both_inputStream_V_dest_V_U->ap_clk(ap_clk);
    regslice_both_inputStream_V_dest_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_inputStream_V_dest_V_U->data_in(inputStream_TDEST);
    regslice_both_inputStream_V_dest_V_U->vld_in(inputStream_TVALID);
    regslice_both_inputStream_V_dest_V_U->ack_in(regslice_both_inputStream_V_dest_V_U_ack_in);
    regslice_both_inputStream_V_dest_V_U->data_out(inputStream_TDEST_int);
    regslice_both_inputStream_V_dest_V_U->vld_out(regslice_both_inputStream_V_dest_V_U_vld_out);
    regslice_both_inputStream_V_dest_V_U->ack_out(inputStream_TREADY_int);
    regslice_both_inputStream_V_dest_V_U->apdone_blk(regslice_both_inputStream_V_dest_V_U_apdone_blk);
    regslice_both_outputStream_V_data_V_U = new regslice_both<32>("regslice_both_outputStream_V_data_V_U");
    regslice_both_outputStream_V_data_V_U->ap_clk(ap_clk);
    regslice_both_outputStream_V_data_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_outputStream_V_data_V_U->data_in(grp_method1_fu_54_outputStream_TDATA);
    regslice_both_outputStream_V_data_V_U->vld_in(grp_method1_fu_54_outputStream_TVALID);
    regslice_both_outputStream_V_data_V_U->ack_in(outputStream_TREADY_int);
    regslice_both_outputStream_V_data_V_U->data_out(outputStream_TDATA);
    regslice_both_outputStream_V_data_V_U->vld_out(regslice_both_outputStream_V_data_V_U_vld_out);
    regslice_both_outputStream_V_data_V_U->ack_out(outputStream_TREADY);
    regslice_both_outputStream_V_data_V_U->apdone_blk(regslice_both_outputStream_V_data_V_U_apdone_blk);
    regslice_both_outputStream_V_keep_V_U = new regslice_both<4>("regslice_both_outputStream_V_keep_V_U");
    regslice_both_outputStream_V_keep_V_U->ap_clk(ap_clk);
    regslice_both_outputStream_V_keep_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_outputStream_V_keep_V_U->data_in(grp_method1_fu_54_outputStream_TKEEP);
    regslice_both_outputStream_V_keep_V_U->vld_in(grp_method1_fu_54_outputStream_TVALID);
    regslice_both_outputStream_V_keep_V_U->ack_in(regslice_both_outputStream_V_keep_V_U_ack_in_dummy);
    regslice_both_outputStream_V_keep_V_U->data_out(outputStream_TKEEP);
    regslice_both_outputStream_V_keep_V_U->vld_out(regslice_both_outputStream_V_keep_V_U_vld_out);
    regslice_both_outputStream_V_keep_V_U->ack_out(outputStream_TREADY);
    regslice_both_outputStream_V_keep_V_U->apdone_blk(regslice_both_outputStream_V_keep_V_U_apdone_blk);
    regslice_both_outputStream_V_strb_V_U = new regslice_both<4>("regslice_both_outputStream_V_strb_V_U");
    regslice_both_outputStream_V_strb_V_U->ap_clk(ap_clk);
    regslice_both_outputStream_V_strb_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_outputStream_V_strb_V_U->data_in(grp_method1_fu_54_outputStream_TSTRB);
    regslice_both_outputStream_V_strb_V_U->vld_in(grp_method1_fu_54_outputStream_TVALID);
    regslice_both_outputStream_V_strb_V_U->ack_in(regslice_both_outputStream_V_strb_V_U_ack_in_dummy);
    regslice_both_outputStream_V_strb_V_U->data_out(outputStream_TSTRB);
    regslice_both_outputStream_V_strb_V_U->vld_out(regslice_both_outputStream_V_strb_V_U_vld_out);
    regslice_both_outputStream_V_strb_V_U->ack_out(outputStream_TREADY);
    regslice_both_outputStream_V_strb_V_U->apdone_blk(regslice_both_outputStream_V_strb_V_U_apdone_blk);
    regslice_both_outputStream_V_user_V_U = new regslice_both<1>("regslice_both_outputStream_V_user_V_U");
    regslice_both_outputStream_V_user_V_U->ap_clk(ap_clk);
    regslice_both_outputStream_V_user_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_outputStream_V_user_V_U->data_in(grp_method1_fu_54_outputStream_TUSER);
    regslice_both_outputStream_V_user_V_U->vld_in(grp_method1_fu_54_outputStream_TVALID);
    regslice_both_outputStream_V_user_V_U->ack_in(regslice_both_outputStream_V_user_V_U_ack_in_dummy);
    regslice_both_outputStream_V_user_V_U->data_out(outputStream_TUSER);
    regslice_both_outputStream_V_user_V_U->vld_out(regslice_both_outputStream_V_user_V_U_vld_out);
    regslice_both_outputStream_V_user_V_U->ack_out(outputStream_TREADY);
    regslice_both_outputStream_V_user_V_U->apdone_blk(regslice_both_outputStream_V_user_V_U_apdone_blk);
    regslice_both_outputStream_V_last_V_U = new regslice_both<1>("regslice_both_outputStream_V_last_V_U");
    regslice_both_outputStream_V_last_V_U->ap_clk(ap_clk);
    regslice_both_outputStream_V_last_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_outputStream_V_last_V_U->data_in(grp_method1_fu_54_outputStream_TLAST);
    regslice_both_outputStream_V_last_V_U->vld_in(grp_method1_fu_54_outputStream_TVALID);
    regslice_both_outputStream_V_last_V_U->ack_in(regslice_both_outputStream_V_last_V_U_ack_in_dummy);
    regslice_both_outputStream_V_last_V_U->data_out(outputStream_TLAST);
    regslice_both_outputStream_V_last_V_U->vld_out(regslice_both_outputStream_V_last_V_U_vld_out);
    regslice_both_outputStream_V_last_V_U->ack_out(outputStream_TREADY);
    regslice_both_outputStream_V_last_V_U->apdone_blk(regslice_both_outputStream_V_last_V_U_apdone_blk);
    regslice_both_outputStream_V_id_V_U = new regslice_both<1>("regslice_both_outputStream_V_id_V_U");
    regslice_both_outputStream_V_id_V_U->ap_clk(ap_clk);
    regslice_both_outputStream_V_id_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_outputStream_V_id_V_U->data_in(grp_method1_fu_54_outputStream_TID);
    regslice_both_outputStream_V_id_V_U->vld_in(grp_method1_fu_54_outputStream_TVALID);
    regslice_both_outputStream_V_id_V_U->ack_in(regslice_both_outputStream_V_id_V_U_ack_in_dummy);
    regslice_both_outputStream_V_id_V_U->data_out(outputStream_TID);
    regslice_both_outputStream_V_id_V_U->vld_out(regslice_both_outputStream_V_id_V_U_vld_out);
    regslice_both_outputStream_V_id_V_U->ack_out(outputStream_TREADY);
    regslice_both_outputStream_V_id_V_U->apdone_blk(regslice_both_outputStream_V_id_V_U_apdone_blk);
    regslice_both_outputStream_V_dest_V_U = new regslice_both<1>("regslice_both_outputStream_V_dest_V_U");
    regslice_both_outputStream_V_dest_V_U->ap_clk(ap_clk);
    regslice_both_outputStream_V_dest_V_U->ap_rst(ap_rst_n_inv);
    regslice_both_outputStream_V_dest_V_U->data_in(grp_method1_fu_54_outputStream_TDEST);
    regslice_both_outputStream_V_dest_V_U->vld_in(grp_method1_fu_54_outputStream_TVALID);
    regslice_both_outputStream_V_dest_V_U->ack_in(regslice_both_outputStream_V_dest_V_U_ack_in_dummy);
    regslice_both_outputStream_V_dest_V_U->data_out(outputStream_TDEST);
    regslice_both_outputStream_V_dest_V_U->vld_out(regslice_both_outputStream_V_dest_V_U_vld_out);
    regslice_both_outputStream_V_dest_V_U->ack_out(outputStream_TREADY);
    regslice_both_outputStream_V_dest_V_U->apdone_blk(regslice_both_outputStream_V_dest_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state3_on_subcall_done);
    sensitive << ( ap_sync_grp_method1_fu_54_ap_ready );
    sensitive << ( ap_sync_grp_method1_fu_54_ap_done );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_grp_method1_fu_54_ap_done);
    sensitive << ( grp_method1_fu_54_ap_done );
    sensitive << ( ap_sync_reg_grp_method1_fu_54_ap_done );

    SC_METHOD(thread_ap_sync_grp_method1_fu_54_ap_ready);
    sensitive << ( grp_method1_fu_54_ap_ready );
    sensitive << ( ap_sync_reg_grp_method1_fu_54_ap_ready );

    SC_METHOD(thread_grp_method1_fu_54_ap_continue);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_block_state3_on_subcall_done );

    SC_METHOD(thread_grp_method1_fu_54_ap_start);
    sensitive << ( grp_method1_fu_54_ap_start_reg );

    SC_METHOD(thread_grp_method1_fu_54_outputStream_TREADY);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( outputStream_TREADY_int );

    SC_METHOD(thread_inputStream_TREADY);
    sensitive << ( inputStream_TVALID );
    sensitive << ( regslice_both_inputStream_V_data_V_U_ack_in );

    SC_METHOD(thread_inputStream_TREADY_int);
    sensitive << ( grp_method1_fu_54_inputStream_TREADY );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_outputStream_TVALID);
    sensitive << ( regslice_both_outputStream_V_data_V_U_vld_out );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_block_state3_on_subcall_done );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( regslice_both_outputStream_V_data_V_U_apdone_blk );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    grp_method1_fu_54_ap_start_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_sync_reg_grp_method1_fu_54_ap_ready = SC_LOGIC_0;
    ap_sync_reg_grp_method1_fu_54_ap_done = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "top_level_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, inputStream_TDATA, "(port)inputStream_TDATA");
    sc_trace(mVcdFile, inputStream_TVALID, "(port)inputStream_TVALID");
    sc_trace(mVcdFile, inputStream_TREADY, "(port)inputStream_TREADY");
    sc_trace(mVcdFile, inputStream_TKEEP, "(port)inputStream_TKEEP");
    sc_trace(mVcdFile, inputStream_TSTRB, "(port)inputStream_TSTRB");
    sc_trace(mVcdFile, inputStream_TUSER, "(port)inputStream_TUSER");
    sc_trace(mVcdFile, inputStream_TLAST, "(port)inputStream_TLAST");
    sc_trace(mVcdFile, inputStream_TID, "(port)inputStream_TID");
    sc_trace(mVcdFile, inputStream_TDEST, "(port)inputStream_TDEST");
    sc_trace(mVcdFile, outputStream_TDATA, "(port)outputStream_TDATA");
    sc_trace(mVcdFile, outputStream_TVALID, "(port)outputStream_TVALID");
    sc_trace(mVcdFile, outputStream_TREADY, "(port)outputStream_TREADY");
    sc_trace(mVcdFile, outputStream_TKEEP, "(port)outputStream_TKEEP");
    sc_trace(mVcdFile, outputStream_TSTRB, "(port)outputStream_TSTRB");
    sc_trace(mVcdFile, outputStream_TUSER, "(port)outputStream_TUSER");
    sc_trace(mVcdFile, outputStream_TLAST, "(port)outputStream_TLAST");
    sc_trace(mVcdFile, outputStream_TID, "(port)outputStream_TID");
    sc_trace(mVcdFile, outputStream_TDEST, "(port)outputStream_TDEST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, grp_method1_fu_54_outputStream_TDATA, "grp_method1_fu_54_outputStream_TDATA");
    sc_trace(mVcdFile, grp_method1_fu_54_outputStream_TKEEP, "grp_method1_fu_54_outputStream_TKEEP");
    sc_trace(mVcdFile, grp_method1_fu_54_outputStream_TSTRB, "grp_method1_fu_54_outputStream_TSTRB");
    sc_trace(mVcdFile, grp_method1_fu_54_outputStream_TUSER, "grp_method1_fu_54_outputStream_TUSER");
    sc_trace(mVcdFile, grp_method1_fu_54_outputStream_TLAST, "grp_method1_fu_54_outputStream_TLAST");
    sc_trace(mVcdFile, grp_method1_fu_54_outputStream_TID, "grp_method1_fu_54_outputStream_TID");
    sc_trace(mVcdFile, grp_method1_fu_54_outputStream_TDEST, "grp_method1_fu_54_outputStream_TDEST");
    sc_trace(mVcdFile, grp_method1_fu_54_ap_start, "grp_method1_fu_54_ap_start");
    sc_trace(mVcdFile, grp_method1_fu_54_inputStream_TREADY, "grp_method1_fu_54_inputStream_TREADY");
    sc_trace(mVcdFile, grp_method1_fu_54_outputStream_TVALID, "grp_method1_fu_54_outputStream_TVALID");
    sc_trace(mVcdFile, grp_method1_fu_54_outputStream_TREADY, "grp_method1_fu_54_outputStream_TREADY");
    sc_trace(mVcdFile, grp_method1_fu_54_ap_done, "grp_method1_fu_54_ap_done");
    sc_trace(mVcdFile, grp_method1_fu_54_ap_ready, "grp_method1_fu_54_ap_ready");
    sc_trace(mVcdFile, grp_method1_fu_54_ap_idle, "grp_method1_fu_54_ap_idle");
    sc_trace(mVcdFile, grp_method1_fu_54_ap_continue, "grp_method1_fu_54_ap_continue");
    sc_trace(mVcdFile, grp_method1_fu_54_ap_start_reg, "grp_method1_fu_54_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_sync_grp_method1_fu_54_ap_ready, "ap_sync_grp_method1_fu_54_ap_ready");
    sc_trace(mVcdFile, ap_sync_grp_method1_fu_54_ap_done, "ap_sync_grp_method1_fu_54_ap_done");
    sc_trace(mVcdFile, ap_block_state3_on_subcall_done, "ap_block_state3_on_subcall_done");
    sc_trace(mVcdFile, ap_sync_reg_grp_method1_fu_54_ap_ready, "ap_sync_reg_grp_method1_fu_54_ap_ready");
    sc_trace(mVcdFile, ap_sync_reg_grp_method1_fu_54_ap_done, "ap_sync_reg_grp_method1_fu_54_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, regslice_both_outputStream_V_data_V_U_apdone_blk, "regslice_both_outputStream_V_data_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_inputStream_V_data_V_U_apdone_blk, "regslice_both_inputStream_V_data_V_U_apdone_blk");
    sc_trace(mVcdFile, inputStream_TDATA_int, "inputStream_TDATA_int");
    sc_trace(mVcdFile, inputStream_TVALID_int, "inputStream_TVALID_int");
    sc_trace(mVcdFile, inputStream_TREADY_int, "inputStream_TREADY_int");
    sc_trace(mVcdFile, regslice_both_inputStream_V_data_V_U_ack_in, "regslice_both_inputStream_V_data_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_inputStream_V_keep_V_U_apdone_blk, "regslice_both_inputStream_V_keep_V_U_apdone_blk");
    sc_trace(mVcdFile, inputStream_TKEEP_int, "inputStream_TKEEP_int");
    sc_trace(mVcdFile, regslice_both_inputStream_V_keep_V_U_vld_out, "regslice_both_inputStream_V_keep_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_inputStream_V_keep_V_U_ack_in, "regslice_both_inputStream_V_keep_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_inputStream_V_strb_V_U_apdone_blk, "regslice_both_inputStream_V_strb_V_U_apdone_blk");
    sc_trace(mVcdFile, inputStream_TSTRB_int, "inputStream_TSTRB_int");
    sc_trace(mVcdFile, regslice_both_inputStream_V_strb_V_U_vld_out, "regslice_both_inputStream_V_strb_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_inputStream_V_strb_V_U_ack_in, "regslice_both_inputStream_V_strb_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_inputStream_V_user_V_U_apdone_blk, "regslice_both_inputStream_V_user_V_U_apdone_blk");
    sc_trace(mVcdFile, inputStream_TUSER_int, "inputStream_TUSER_int");
    sc_trace(mVcdFile, regslice_both_inputStream_V_user_V_U_vld_out, "regslice_both_inputStream_V_user_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_inputStream_V_user_V_U_ack_in, "regslice_both_inputStream_V_user_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_inputStream_V_last_V_U_apdone_blk, "regslice_both_inputStream_V_last_V_U_apdone_blk");
    sc_trace(mVcdFile, inputStream_TLAST_int, "inputStream_TLAST_int");
    sc_trace(mVcdFile, regslice_both_inputStream_V_last_V_U_vld_out, "regslice_both_inputStream_V_last_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_inputStream_V_last_V_U_ack_in, "regslice_both_inputStream_V_last_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_inputStream_V_id_V_U_apdone_blk, "regslice_both_inputStream_V_id_V_U_apdone_blk");
    sc_trace(mVcdFile, inputStream_TID_int, "inputStream_TID_int");
    sc_trace(mVcdFile, regslice_both_inputStream_V_id_V_U_vld_out, "regslice_both_inputStream_V_id_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_inputStream_V_id_V_U_ack_in, "regslice_both_inputStream_V_id_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_inputStream_V_dest_V_U_apdone_blk, "regslice_both_inputStream_V_dest_V_U_apdone_blk");
    sc_trace(mVcdFile, inputStream_TDEST_int, "inputStream_TDEST_int");
    sc_trace(mVcdFile, regslice_both_inputStream_V_dest_V_U_vld_out, "regslice_both_inputStream_V_dest_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_inputStream_V_dest_V_U_ack_in, "regslice_both_inputStream_V_dest_V_U_ack_in");
    sc_trace(mVcdFile, outputStream_TREADY_int, "outputStream_TREADY_int");
    sc_trace(mVcdFile, regslice_both_outputStream_V_data_V_U_vld_out, "regslice_both_outputStream_V_data_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_outputStream_V_keep_V_U_apdone_blk, "regslice_both_outputStream_V_keep_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_outputStream_V_keep_V_U_ack_in_dummy, "regslice_both_outputStream_V_keep_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_outputStream_V_keep_V_U_vld_out, "regslice_both_outputStream_V_keep_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_outputStream_V_strb_V_U_apdone_blk, "regslice_both_outputStream_V_strb_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_outputStream_V_strb_V_U_ack_in_dummy, "regslice_both_outputStream_V_strb_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_outputStream_V_strb_V_U_vld_out, "regslice_both_outputStream_V_strb_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_outputStream_V_user_V_U_apdone_blk, "regslice_both_outputStream_V_user_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_outputStream_V_user_V_U_ack_in_dummy, "regslice_both_outputStream_V_user_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_outputStream_V_user_V_U_vld_out, "regslice_both_outputStream_V_user_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_outputStream_V_last_V_U_apdone_blk, "regslice_both_outputStream_V_last_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_outputStream_V_last_V_U_ack_in_dummy, "regslice_both_outputStream_V_last_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_outputStream_V_last_V_U_vld_out, "regslice_both_outputStream_V_last_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_outputStream_V_id_V_U_apdone_blk, "regslice_both_outputStream_V_id_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_outputStream_V_id_V_U_ack_in_dummy, "regslice_both_outputStream_V_id_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_outputStream_V_id_V_U_vld_out, "regslice_both_outputStream_V_id_V_U_vld_out");
    sc_trace(mVcdFile, regslice_both_outputStream_V_dest_V_U_apdone_blk, "regslice_both_outputStream_V_dest_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_outputStream_V_dest_V_U_ack_in_dummy, "regslice_both_outputStream_V_dest_V_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_outputStream_V_dest_V_U_vld_out, "regslice_both_outputStream_V_dest_V_U_vld_out");
#endif

    }
    mHdltvinHandle.open("top_level.hdltvin.dat");
    mHdltvoutHandle.open("top_level.hdltvout.dat");
}

top_level::~top_level() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_method1_fu_54;
    delete regslice_both_inputStream_V_data_V_U;
    delete regslice_both_inputStream_V_keep_V_U;
    delete regslice_both_inputStream_V_strb_V_U;
    delete regslice_both_inputStream_V_user_V_U;
    delete regslice_both_inputStream_V_last_V_U;
    delete regslice_both_inputStream_V_id_V_U;
    delete regslice_both_inputStream_V_dest_V_U;
    delete regslice_both_outputStream_V_data_V_U;
    delete regslice_both_outputStream_V_keep_V_U;
    delete regslice_both_outputStream_V_strb_V_U;
    delete regslice_both_outputStream_V_user_V_U;
    delete regslice_both_outputStream_V_last_V_U;
    delete regslice_both_outputStream_V_id_V_U;
    delete regslice_both_outputStream_V_dest_V_U;
}

void top_level::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_grp_method1_fu_54_ap_done = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(ap_block_state3_on_subcall_done.read(), ap_const_boolean_0))) {
            ap_sync_reg_grp_method1_fu_54_ap_done = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_method1_fu_54_ap_done.read())) {
            ap_sync_reg_grp_method1_fu_54_ap_done = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_grp_method1_fu_54_ap_ready = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(ap_block_state3_on_subcall_done.read(), ap_const_boolean_0))) {
            ap_sync_reg_grp_method1_fu_54_ap_ready = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_method1_fu_54_ap_ready.read())) {
            ap_sync_reg_grp_method1_fu_54_ap_ready = ap_const_logic_1;
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        grp_method1_fu_54_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_grp_method1_fu_54_ap_ready.read())))) {
            grp_method1_fu_54_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_method1_fu_54_ap_ready.read())) {
            grp_method1_fu_54_ap_start_reg = ap_const_logic_0;
        }
    }
}

void top_level::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void top_level::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void top_level::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void top_level::thread_ap_block_state3_on_subcall_done() {
    ap_block_state3_on_subcall_done = esl_seteq<1,1,1>(ap_const_logic_0, (ap_sync_grp_method1_fu_54_ap_ready.read() & ap_sync_grp_method1_fu_54_ap_done.read()));
}

void top_level::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void top_level::thread_ap_sync_grp_method1_fu_54_ap_done() {
    ap_sync_grp_method1_fu_54_ap_done = (grp_method1_fu_54_ap_done.read() | ap_sync_reg_grp_method1_fu_54_ap_done.read());
}

void top_level::thread_ap_sync_grp_method1_fu_54_ap_ready() {
    ap_sync_grp_method1_fu_54_ap_ready = (grp_method1_fu_54_ap_ready.read() | ap_sync_reg_grp_method1_fu_54_ap_ready.read());
}

void top_level::thread_grp_method1_fu_54_ap_continue() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(ap_block_state3_on_subcall_done.read(), ap_const_boolean_0))) {
        grp_method1_fu_54_ap_continue = ap_const_logic_1;
    } else {
        grp_method1_fu_54_ap_continue = ap_const_logic_0;
    }
}

void top_level::thread_grp_method1_fu_54_ap_start() {
    grp_method1_fu_54_ap_start = grp_method1_fu_54_ap_start_reg.read();
}

void top_level::thread_grp_method1_fu_54_outputStream_TREADY() {
    grp_method1_fu_54_outputStream_TREADY = (ap_CS_fsm_state3.read() & outputStream_TREADY_int.read());
}

void top_level::thread_inputStream_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, inputStream_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_inputStream_V_data_V_U_ack_in.read()))) {
        inputStream_TREADY = ap_const_logic_1;
    } else {
        inputStream_TREADY = ap_const_logic_0;
    }
}

void top_level::thread_inputStream_TREADY_int() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        inputStream_TREADY_int = grp_method1_fu_54_inputStream_TREADY.read();
    } else {
        inputStream_TREADY_int = ap_const_logic_0;
    }
}

void top_level::thread_outputStream_TVALID() {
    outputStream_TVALID = regslice_both_outputStream_V_data_V_U_vld_out.read();
}

void top_level::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_block_state3_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(regslice_both_outputStream_V_data_V_U_apdone_blk.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

void top_level::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inputStream_TDATA\" :  \"" << inputStream_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inputStream_TVALID\" :  \"" << inputStream_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"inputStream_TREADY\" :  \"" << inputStream_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inputStream_TKEEP\" :  \"" << inputStream_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inputStream_TSTRB\" :  \"" << inputStream_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inputStream_TUSER\" :  \"" << inputStream_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inputStream_TLAST\" :  \"" << inputStream_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inputStream_TID\" :  \"" << inputStream_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inputStream_TDEST\" :  \"" << inputStream_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outputStream_TDATA\" :  \"" << outputStream_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outputStream_TVALID\" :  \"" << outputStream_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"outputStream_TREADY\" :  \"" << outputStream_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outputStream_TKEEP\" :  \"" << outputStream_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outputStream_TSTRB\" :  \"" << outputStream_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outputStream_TUSER\" :  \"" << outputStream_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outputStream_TLAST\" :  \"" << outputStream_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outputStream_TID\" :  \"" << outputStream_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outputStream_TDEST\" :  \"" << outputStream_TDEST.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

