// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _top_level_HH_
#define _top_level_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "method1.h"

namespace ap_rtl {

struct top_level : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_lv<32> > inputStream_TDATA;
    sc_in< sc_logic > inputStream_TVALID;
    sc_out< sc_logic > inputStream_TREADY;
    sc_in< sc_lv<4> > inputStream_TKEEP;
    sc_in< sc_lv<4> > inputStream_TSTRB;
    sc_in< sc_lv<1> > inputStream_TUSER;
    sc_in< sc_lv<1> > inputStream_TLAST;
    sc_in< sc_lv<1> > inputStream_TID;
    sc_in< sc_lv<1> > inputStream_TDEST;
    sc_out< sc_lv<32> > outputStream_TDATA;
    sc_out< sc_logic > outputStream_TVALID;
    sc_in< sc_logic > outputStream_TREADY;
    sc_out< sc_lv<4> > outputStream_TKEEP;
    sc_out< sc_lv<4> > outputStream_TSTRB;
    sc_out< sc_lv<1> > outputStream_TUSER;
    sc_out< sc_lv<1> > outputStream_TLAST;
    sc_out< sc_lv<1> > outputStream_TID;
    sc_out< sc_lv<1> > outputStream_TDEST;


    // Module declarations
    top_level(sc_module_name name);
    SC_HAS_PROCESS(top_level);

    ~top_level();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    method1* grp_method1_fu_54;
    regslice_both<32>* regslice_both_inputStream_V_data_V_U;
    regslice_both<4>* regslice_both_inputStream_V_keep_V_U;
    regslice_both<4>* regslice_both_inputStream_V_strb_V_U;
    regslice_both<1>* regslice_both_inputStream_V_user_V_U;
    regslice_both<1>* regslice_both_inputStream_V_last_V_U;
    regslice_both<1>* regslice_both_inputStream_V_id_V_U;
    regslice_both<1>* regslice_both_inputStream_V_dest_V_U;
    regslice_both<32>* regslice_both_outputStream_V_data_V_U;
    regslice_both<4>* regslice_both_outputStream_V_keep_V_U;
    regslice_both<4>* regslice_both_outputStream_V_strb_V_U;
    regslice_both<1>* regslice_both_outputStream_V_user_V_U;
    regslice_both<1>* regslice_both_outputStream_V_last_V_U;
    regslice_both<1>* regslice_both_outputStream_V_id_V_U;
    regslice_both<1>* regslice_both_outputStream_V_dest_V_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_lv<32> > grp_method1_fu_54_outputStream_TDATA;
    sc_signal< sc_lv<4> > grp_method1_fu_54_outputStream_TKEEP;
    sc_signal< sc_lv<4> > grp_method1_fu_54_outputStream_TSTRB;
    sc_signal< sc_lv<1> > grp_method1_fu_54_outputStream_TUSER;
    sc_signal< sc_lv<1> > grp_method1_fu_54_outputStream_TLAST;
    sc_signal< sc_lv<1> > grp_method1_fu_54_outputStream_TID;
    sc_signal< sc_lv<1> > grp_method1_fu_54_outputStream_TDEST;
    sc_signal< sc_logic > grp_method1_fu_54_ap_start;
    sc_signal< sc_logic > grp_method1_fu_54_inputStream_TREADY;
    sc_signal< sc_logic > grp_method1_fu_54_outputStream_TVALID;
    sc_signal< sc_logic > grp_method1_fu_54_outputStream_TREADY;
    sc_signal< sc_logic > grp_method1_fu_54_ap_done;
    sc_signal< sc_logic > grp_method1_fu_54_ap_ready;
    sc_signal< sc_logic > grp_method1_fu_54_ap_idle;
    sc_signal< sc_logic > grp_method1_fu_54_ap_continue;
    sc_signal< sc_logic > grp_method1_fu_54_ap_start_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_sync_grp_method1_fu_54_ap_ready;
    sc_signal< sc_logic > ap_sync_grp_method1_fu_54_ap_done;
    sc_signal< bool > ap_block_state3_on_subcall_done;
    sc_signal< sc_logic > ap_sync_reg_grp_method1_fu_54_ap_ready;
    sc_signal< sc_logic > ap_sync_reg_grp_method1_fu_54_ap_done;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > regslice_both_outputStream_V_data_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_inputStream_V_data_V_U_apdone_blk;
    sc_signal< sc_lv<32> > inputStream_TDATA_int;
    sc_signal< sc_logic > inputStream_TVALID_int;
    sc_signal< sc_logic > inputStream_TREADY_int;
    sc_signal< sc_logic > regslice_both_inputStream_V_data_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inputStream_V_keep_V_U_apdone_blk;
    sc_signal< sc_lv<4> > inputStream_TKEEP_int;
    sc_signal< sc_logic > regslice_both_inputStream_V_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inputStream_V_keep_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inputStream_V_strb_V_U_apdone_blk;
    sc_signal< sc_lv<4> > inputStream_TSTRB_int;
    sc_signal< sc_logic > regslice_both_inputStream_V_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inputStream_V_strb_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inputStream_V_user_V_U_apdone_blk;
    sc_signal< sc_lv<1> > inputStream_TUSER_int;
    sc_signal< sc_logic > regslice_both_inputStream_V_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inputStream_V_user_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inputStream_V_last_V_U_apdone_blk;
    sc_signal< sc_lv<1> > inputStream_TLAST_int;
    sc_signal< sc_logic > regslice_both_inputStream_V_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inputStream_V_last_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inputStream_V_id_V_U_apdone_blk;
    sc_signal< sc_lv<1> > inputStream_TID_int;
    sc_signal< sc_logic > regslice_both_inputStream_V_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inputStream_V_id_V_U_ack_in;
    sc_signal< sc_logic > regslice_both_inputStream_V_dest_V_U_apdone_blk;
    sc_signal< sc_lv<1> > inputStream_TDEST_int;
    sc_signal< sc_logic > regslice_both_inputStream_V_dest_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_inputStream_V_dest_V_U_ack_in;
    sc_signal< sc_logic > outputStream_TREADY_int;
    sc_signal< sc_logic > regslice_both_outputStream_V_data_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outputStream_V_keep_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outputStream_V_keep_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outputStream_V_keep_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outputStream_V_strb_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outputStream_V_strb_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outputStream_V_strb_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outputStream_V_user_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outputStream_V_user_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outputStream_V_user_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outputStream_V_last_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outputStream_V_last_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outputStream_V_last_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outputStream_V_id_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outputStream_V_id_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outputStream_V_id_V_U_vld_out;
    sc_signal< sc_logic > regslice_both_outputStream_V_dest_V_U_apdone_blk;
    sc_signal< sc_logic > regslice_both_outputStream_V_dest_V_U_ack_in_dummy;
    sc_signal< sc_logic > regslice_both_outputStream_V_dest_V_U_vld_out;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const bool ap_const_boolean_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_block_state3_on_subcall_done();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_grp_method1_fu_54_ap_done();
    void thread_ap_sync_grp_method1_fu_54_ap_ready();
    void thread_grp_method1_fu_54_ap_continue();
    void thread_grp_method1_fu_54_ap_start();
    void thread_grp_method1_fu_54_outputStream_TREADY();
    void thread_inputStream_TREADY();
    void thread_inputStream_TREADY_int();
    void thread_outputStream_TVALID();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
